package com.authx.clustertest.report;

import com.authx.clustertest.config.ResultsRepo;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 生成一份自包含的中文 HTML 集群压测报告。
 * 内嵌 Chart.js 和全部 JSON 数据，离线浏览器可直接打开。
 */
@Component
public class HtmlReportGenerator {
    private final ResultsRepo repo;
    private final EnvironmentInfo env;
    private final ObjectMapper mapper = new ObjectMapper();

    public HtmlReportGenerator(ResultsRepo r, EnvironmentInfo e) {
        this.repo = r; this.env = e;
    }

    @SuppressWarnings("rawtypes")
    public Path generate() throws IOException {
        String chartJs = new String(
                new ClassPathResource("web/chart.min.js").getInputStream().readAllBytes());

        var data = new LinkedHashMap<String, Object>();
        data.put("env", env.snapshot());
        data.put("correctness", repo.read("correctness", Map.class));
        data.put("baseline", repo.read("baseline", Map.class));
        data.put("resilience", repo.read("resilience", Map.class));
        data.put("stress", repo.read("stress", Map.class));
        data.put("soak", repo.read("soak", Map.class));

        String json = mapper.writeValueAsString(data);
        String html = buildHtml(chartJs, json);

        Path out = repo.baseDir().resolveSibling("report.html");
        Files.writeString(out, html);
        return out;
    }

    private String buildHtml(String chartJs, String json) {
        return "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
                + "<title>AuthX SDK 集群压测报告</title>"
                + "<style>" + CSS + "</style>"
                + "<script>" + chartJs + "</script>"
                + "</head><body>"
                + "<div class=\"page\">"
                + "<header><h1>AuthX SDK 集群压测报告</h1>"
                + "<div class=\"subtitle\" id=\"subtitle\"></div></header>"
                + "<main id=\"root\"></main>"
                + "<footer>Generated by AuthX SDK cluster-test · Chart.js v4 · 离线可浏览</footer>"
                + "</div>"
                + "<script>const DATA = " + json + ";\n" + RENDER_JS + "\nrenderReport(DATA);</script>"
                + "</body></html>";
    }

    private static final String CSS = """
            :root {
              --bg: #f7f8fa;
              --card: #ffffff;
              --ink: #1f2937;
              --ink-dim: #4b5563;
              --ink-soft: #6b7280;
              --border: #e5e7eb;
              --brand: #0a5bce;
              --brand-soft: #e8f0fe;
              --pass: #10b981;
              --pass-bg: #d1fae5;
              --fail: #ef4444;
              --fail-bg: #fee2e2;
              --warn: #f59e0b;
              --warn-bg: #fef3c7;
              --skip: #9ca3af;
              --skip-bg: #f3f4f6;
            }
            *{box-sizing:border-box}
            body{font-family:-apple-system,"PingFang SC","Microsoft YaHei",Segoe UI,sans-serif;
                 margin:0;background:var(--bg);color:var(--ink);line-height:1.6}
            .page{max-width:1200px;margin:0 auto;padding:32px 24px}
            header{border-bottom:3px solid var(--brand);padding-bottom:16px;margin-bottom:24px}
            h1{margin:0;font-size:28px;color:var(--ink)}
            .subtitle{color:var(--ink-soft);font-size:14px;margin-top:8px}
            footer{margin-top:48px;padding-top:16px;border-top:1px solid var(--border);
                   color:var(--ink-soft);font-size:12px;text-align:center}
            section{background:var(--card);border:1px solid var(--border);border-radius:12px;
                    padding:24px;margin-bottom:24px;box-shadow:0 1px 3px rgba(0,0,0,0.04)}
            section h2{margin:0 0 16px 0;font-size:20px;color:var(--brand);
                       padding-bottom:8px;border-bottom:1px solid var(--border)}
            section h3{margin:20px 0 10px 0;font-size:15px;color:var(--ink-dim);font-weight:600}
            table{border-collapse:collapse;width:100%;margin:8px 0;font-size:14px}
            th{background:#f9fafb;font-weight:600;text-align:left;padding:10px 14px;
               border-bottom:2px solid var(--border);color:var(--ink-dim)}
            td{padding:10px 14px;border-bottom:1px solid var(--border);vertical-align:top}
            tr:last-child td{border-bottom:none}
            tr.pass td:first-child::before{content:"✓ ";color:var(--pass);font-weight:bold}
            tr.fail td:first-child::before{content:"✗ ";color:var(--fail);font-weight:bold}
            tr.skip td:first-child::before{content:"○ ";color:var(--skip);font-weight:bold}
            .badge{display:inline-block;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600}
            .badge.pass{background:var(--pass-bg);color:#047857}
            .badge.fail{background:var(--fail-bg);color:#b91c1c}
            .badge.skip{background:var(--skip-bg);color:#4b5563}
            .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:16px 0}
            .card{background:var(--brand-soft);border-radius:10px;padding:16px;border:1px solid #d0dffb}
            .card .num{font-size:28px;font-weight:700;color:var(--brand)}
            .card .label{font-size:12px;color:var(--ink-soft);margin-top:4px;text-transform:uppercase;letter-spacing:0.5px}
            .card.pass{background:var(--pass-bg);border-color:#a7f3d0}
            .card.pass .num{color:#047857}
            .card.fail{background:var(--fail-bg);border-color:#fecaca}
            .card.fail .num{color:#b91c1c}
            canvas{max-width:100%;margin:16px 0}
            .chart-wrap{background:#fbfcfd;border:1px solid var(--border);border-radius:8px;padding:16px;margin:16px 0}
            .kv{display:grid;grid-template-columns:auto 1fr;gap:8px 16px;font-size:13px;
                background:#fbfcfd;padding:12px;border-radius:6px;border:1px solid var(--border)}
            .kv dt{color:var(--ink-soft);font-weight:500}
            .kv dd{margin:0;color:var(--ink);font-family:ui-monospace,"SF Mono",Menlo,monospace}
            .num-cell{font-family:ui-monospace,"SF Mono",Menlo,monospace;text-align:right}
            .note{background:var(--warn-bg);border-left:4px solid var(--warn);padding:10px 14px;
                  border-radius:4px;margin:12px 0;font-size:13px;color:#92400e}
            details{margin:8px 0}
            details summary{cursor:pointer;color:var(--ink-dim);font-size:13px}
            details pre{margin:8px 0 0 0;padding:12px;background:#f3f4f6;border-radius:6px;
                        font-size:12px;overflow:auto;max-height:280px}
            """;

    private static final String RENDER_JS = """
            function renderReport(d){
              const r=document.getElementById('root');
              document.getElementById('subtitle').textContent = '生成时间 ' + (d.env && d.env.generatedAt || '-');
              r.innerHTML += renderSummary(d);
              r.innerHTML += renderEnv(d.env);
              r.innerHTML += renderCorrectness(d.correctness);
              r.innerHTML += renderBaseline(d.baseline);
              r.innerHTML += renderResilience(d.resilience);
              r.innerHTML += renderStress(d.stress);
              r.innerHTML += renderSoak(d.soak);
              drawCharts(d);
            }

            function renderSummary(d){
              const c=d.correctness||{};
              const r=d.resilience||{};
              const rArr = r && typeof r==='object' ? Object.values(r) : [];
              const cPass = c.passed||0, cTotal = c.total||0;
              const rPass = rArr.filter(x=>x && x.status==='PASS').length;
              const rTotal = rArr.length;
              const bTotal = d.baseline ? Object.keys(d.baseline).length : 0;
              const stressDone = d.stress && Object.keys(d.stress).length > 0;
              const soakOps = d.soak && d.soak.ops ? d.soak.ops : 0;
              return `<section>
                <h2>执行摘要</h2>
                <div class="cards">
                  <div class="card ${cPass===cTotal&&cTotal?'pass':(cTotal?'fail':'')}">
                    <div class="num">${cPass}/${cTotal}</div>
                    <div class="label">正确性通过</div>
                  </div>
                  <div class="card ${rPass===rTotal&&rTotal?'pass':(rTotal?'fail':'')}">
                    <div class="num">${rPass}/${rTotal}</div>
                    <div class="label">韧性通过</div>
                  </div>
                  <div class="card">
                    <div class="num">${bTotal}</div>
                    <div class="label">基准场景</div>
                  </div>
                  <div class="card">
                    <div class="num">${stressDone?'完成':'—'}</div>
                    <div class="label">压力测试</div>
                  </div>
                  <div class="card">
                    <div class="num">${(soakOps/1000).toFixed(1)}k</div>
                    <div class="label">浸泡操作数</div>
                  </div>
                </div>
              </section>`;
            }

            function renderEnv(e){
              if(!e) return '';
              const rows = Object.entries(e).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');
              return `<section><h2>运行环境</h2><dl class="kv">${rows}</dl></section>`;
            }

            function renderCorrectness(c){
              if(!c || !c.results) return '';
              const rows = c.results.map(x=>{
                const cls = x.status==='PASS'?'pass':'fail';
                return `<tr class="${cls}">
                  <td>${esc(x.name)}</td>
                  <td><span class="badge ${cls}">${x.status==='PASS'?'通过':'失败'}</span></td>
                  <td class="num-cell">${x.durationMs} ms</td>
                  <td>${esc(x.details||'—')}</td>
                </tr>`;
              }).join('');
              return `<section><h2>正确性测试 C1–C8</h2>
                <p>验证 SDK 的业务语义：授权/撤销、组继承、深层文件夹、Caveat、过期、跨实例、批量原子性。</p>
                <table>
                  <tr><th>场景</th><th>状态</th><th>耗时</th><th>详情</th></tr>
                  ${rows}
                </table></section>`;
            }

            function renderBaseline(b){
              if(!b || !Object.keys(b).length) return '';
              const labels = {
                'B1':'B1 读压测 (70% check)',
                'B2':'B2 写压测 (grant/revoke)',
                'B3':'B3 跨实例一致性',
                'B4':'B4 深层继承',
                'B5':'B5 批量操作'
              };
              const rows = Object.entries(b).map(([k,v])=>{
                return `<tr>
                  <td>${esc(labels[k]||k)}</td>
                  <td class="num-cell">${v.threads}</td>
                  <td class="num-cell"><strong>${v.tps.toFixed(1)}</strong></td>
                  <td class="num-cell">${(v.p50us/1000).toFixed(1)}</td>
                  <td class="num-cell">${(v.p99us/1000).toFixed(1)}</td>
                  <td class="num-cell">${(v.p999us/1000).toFixed(1)}</td>
                  <td class="num-cell">${v.errors}</td>
                </tr>`;
              }).join('');
              return `<section><h2>基线性能 B1–B5</h2>
                <p>3 个 SDK 实例并行打压 3 节点 SpiceDB，各场景各 30 秒。</p>
                <table>
                  <tr><th>场景</th><th>并发</th><th>TPS</th><th>p50 (ms)</th><th>p99 (ms)</th><th>p999 (ms)</th><th>错误</th></tr>
                  ${rows}
                </table>
                <div class="chart-wrap">
                  <h3>吞吐 & 延迟对比</h3>
                  <canvas id="baselineChart"></canvas>
                </div></section>`;
            }

            function renderResilience(r){
              if(!r || !Object.keys(r).length) return '';
              const labels = {
                'R1':'R1 流早退无泄漏',
                'R4':'R4 TokenStore 事件可观测',
                'R5':'R5 并发读写一致性',
                'R6':'R6 熔断器多租户 W-TinyLFU',
                'R7':'R7 close 异常健壮'
              };
              const order = ['R1','R4','R5','R6','R7'];
              const rows = order.filter(k=>r[k]).map(k=>{
                const v = r[k];
                const cls = v.status==='PASS'?'pass':(v.status==='SKIPPED'?'skip':'fail');
                const zh = v.status==='PASS'?'通过':(v.status==='SKIPPED'?'跳过':'失败');
                return `<tr class="${cls}">
                  <td>${esc(labels[k]||k)}</td>
                  <td><span class="badge ${cls}">${zh}</span></td>
                  <td class="num-cell">${v.durationMs} ms</td>
                  <td>
                    <details>
                      <summary>注入参数 / 观察结果 (${Object.keys(v.observed||{}).length} 个指标)</summary>
                      <pre>${esc(JSON.stringify({injection:v.injection,observed:v.observed,events:v.events,reason:v.reason},null,2))}</pre>
                    </details>
                  </td>
                </tr>`;
              }).join('');
              return `<section><h2>韧性测试 R1–R7（P0/P1 风险修复验证）</h2>
                <p>每个测试对应本轮代码审计修复的一个风险点。通过 Toxiproxy 注入网络故障、高并发压力或显式 mock 来验证修复生效。</p>
                <table>
                  <tr><th>场景</th><th>状态</th><th>耗时</th><th>详情</th></tr>
                  ${rows}
                </table></section>`;
            }

            function renderStress(s){
              if(!s) return '';
              const s1 = s.S1 || []; const s2 = s.S2;
              let html = '<section><h2>压力测试 S1 / S2</h2>';
              if(s1.length){
                html += '<h3>S1 并发斜坡（找拐点）</h3><table>'
                  + '<tr><th>并发数</th><th>TPS</th><th>p50 (ms)</th><th>p99 (ms)</th><th>错误</th></tr>'
                  + s1.map(r=>`<tr>
                      <td class="num-cell">${r.threads}</td>
                      <td class="num-cell"><strong>${r.tps.toFixed(1)}</strong></td>
                      <td class="num-cell">${(r.p50us/1000).toFixed(1)}</td>
                      <td class="num-cell">${(r.p99us/1000).toFixed(1)}</td>
                      <td class="num-cell">${r.errors}</td>
                    </tr>`).join('')
                  + '</table>'
                  + '<div class="chart-wrap"><canvas id="stressChart"></canvas></div>';
              }
              if(s2){
                html += `<h3>S2 持续最大 TPS</h3>
                  <dl class="kv">
                    <dt>并发</dt><dd>${s2.threads}</dd>
                    <dt>持续</dt><dd>${(s2.durationMs/1000).toFixed(0)} 秒</dd>
                    <dt>吞吐</dt><dd><strong>${s2.tps.toFixed(1)}</strong> TPS</dd>
                    <dt>p99</dt><dd>${(s2.p99us/1000).toFixed(1)} ms</dd>
                    <dt>错误数</dt><dd>${s2.errors.toLocaleString()}</dd>
                    ${s2.errors > 0 ? '<dt>错误类型</dt><dd>' + Object.entries(s2.errorsByType||{}).map(([k,v])=>`${esc(k)}=${v.toLocaleString()}`).join(', ') + '</dd>' : ''}
                  </dl>`;
                if(s2.errors > s2.ops){
                  html += '<div class="note">⚠ 错误数远超成功操作 — 熔断器在高并发下被触发，fail-fast 保护 SpiceDB 免于过载。这是 P1 修复 #6 的设计行为。</div>';
                }
              }
              return html + '</section>';
            }

            function renderSoak(s){
              if(!s) return '';
              const hasSamples = s.samples && s.samples.length;
              return `<section><h2>浸泡测试 L1（长跑稳定性）</h2>
                <dl class="kv">
                  <dt>持续时长</dt><dd>${s.durationMinutes} 分钟（${(s.durationMs/1000).toFixed(0)} 秒）</dd>
                  <dt>目标 TPS</dt><dd>${s.targetTps||'—'}</dd>
                  <dt>实际 TPS</dt><dd><strong>${(s.achievedTps||0).toFixed(1)}</strong></dd>
                  <dt>总操作数</dt><dd>${(s.ops||0).toLocaleString()}</dd>
                  <dt>错误数</dt><dd>${(s.errors||0).toLocaleString()}</dd>
                </dl>
                ${hasSamples ? '<div class="chart-wrap"><canvas id="soakChart"></canvas></div>' : ''}
              </section>`;
            }

            function drawCharts(d){
              if(d.baseline && Object.keys(d.baseline).length){
                const ctx = document.getElementById('baselineChart');
                if(ctx) new Chart(ctx, {
                  type: 'bar',
                  data: {
                    labels: Object.keys(d.baseline),
                    datasets: [
                      {label:'TPS',data:Object.values(d.baseline).map(v=>v.tps),
                       backgroundColor:'rgba(10,91,206,0.7)', yAxisID:'y'},
                      {label:'p99 (ms)',data:Object.values(d.baseline).map(v=>v.p99us/1000),
                       backgroundColor:'rgba(239,68,68,0.7)', yAxisID:'y2'}
                    ]
                  },
                  options: {
                    responsive: true, maintainAspectRatio: false,
                    scales: {
                      y: {beginAtZero:true, position:'left', title:{display:true,text:'TPS'}},
                      y2: {beginAtZero:true, position:'right', title:{display:true,text:'p99 延迟 (ms)'},
                           grid:{drawOnChartArea:false}}
                    }
                  }
                });
                ctx.parentElement.style.height = '320px';
              }
              if(d.stress && d.stress.S1 && d.stress.S1.length){
                const ctx = document.getElementById('stressChart');
                if(ctx) new Chart(ctx, {
                  type: 'line',
                  data: {
                    labels: d.stress.S1.map(r=>r.threads),
                    datasets: [
                      {label:'TPS',data:d.stress.S1.map(r=>r.tps),
                       borderColor:'#0a5bce',backgroundColor:'rgba(10,91,206,0.1)',tension:0.3,yAxisID:'y'},
                      {label:'p99 (ms)',data:d.stress.S1.map(r=>r.p99us/1000),
                       borderColor:'#ef4444',backgroundColor:'rgba(239,68,68,0.1)',tension:0.3,yAxisID:'y2'}
                    ]
                  },
                  options: {
                    responsive: true, maintainAspectRatio: false,
                    scales: {
                      x: {title:{display:true,text:'并发线程数'}},
                      y: {beginAtZero:true, position:'left', title:{display:true,text:'TPS'}},
                      y2: {beginAtZero:true, position:'right', title:{display:true,text:'p99 延迟 (ms)'},
                           grid:{drawOnChartArea:false}}
                    }
                  }
                });
                ctx.parentElement.style.height = '320px';
              }
              if(d.soak && d.soak.samples && d.soak.samples.length){
                const ctx = document.getElementById('soakChart');
                if(ctx) new Chart(ctx, {
                  type: 'line',
                  data: {
                    labels: d.soak.samples.map(s=>s.tsSec+'s'),
                    datasets: [
                      {label:'堆 MB',data:d.soak.samples.map(s=>s.heapMB),
                       borderColor:'#0a5bce',yAxisID:'y'},
                      {label:'线程数',data:d.soak.samples.map(s=>s.threads),
                       borderColor:'#f59e0b',yAxisID:'y2'}
                    ]
                  },
                  options: {
                    responsive: true, maintainAspectRatio: false,
                    scales: {
                      y: {beginAtZero:true, position:'left', title:{display:true,text:'堆内存 (MB)'}},
                      y2: {beginAtZero:true, position:'right', title:{display:true,text:'线程数'},
                           grid:{drawOnChartArea:false}}
                    }
                  }
                });
                ctx.parentElement.style.height = '320px';
              }
            }

            function esc(s){
              if(s===null||s===undefined) return '';
              return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
                              .replace(/"/g,'&quot;').replace(/'/g,'&#39;');
            }
            """;
}
