package com.authx.testapp.schema;

/**
 * Canonical caveat names from the SpiceDB schema.
 * Generated by AuthxCodegen — do not edit.
 */
public final class Caveats {

    public static final String IP_ALLOWLIST = "ip_allowlist";

    private Caveats() {}
}
