package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.testapp.schema.constants.Department;

/**
 * Typed resource facade for <b>department</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * DepartmentResource doc = new DepartmentResource(client);
 * doc.select("id").grant(Department.Rel.EDITOR).toUser("bob");
 * boolean ok = doc.select("id").check(Department.Perm.VIEW).by("alice");
 * </pre>
 */
public final class DepartmentResource extends TypedResourceFactory<Department.Rel, Department.Perm> {

    public DepartmentResource(AuthxClient client) {
        init("department", client);
    }
}
