package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.ResourceFactory;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.testapp.schema.constants.Department;

/**
 * Type-safe resource factory for <b>department</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * DepartmentResource doc = new DepartmentResource(client);
 * doc.on("doc-1").grant(Department.Rel.EDITOR).toUser("bob");
 * doc.on("doc-1").grant(Department.Rel.EDITOR, Department.Rel.COMMENTER).toUser("bob");
 * doc.on("doc-1").check(Department.Perm.VIEW).by("alice");
 * doc.on("doc-1").revoke(Department.Rel.EDITOR).fromUser("bob");
 * </pre>
 */
public class DepartmentResource extends TypedResourceFactory<Department.Rel, Department.Perm> {

    public DepartmentResource(AuthxClient client) {
        init("department", client);
    }

    @Override
    public DepartmentHandle on(String id) {
        return new DepartmentHandle(this, id);
    }

    public static class DepartmentHandle extends TypedHandle<Department.Rel, Department.Perm> {

        public DepartmentHandle(ResourceFactory factory, String id) {
            super(factory, id);
        }

        @Override @SuppressWarnings("unchecked")
        public DepartmentGrantAction grant(Department.Rel... relations) {
            return new DepartmentGrantAction(factory, id, relations);
        }

        @Override @SuppressWarnings("unchecked")
        public DepartmentRevokeAction revoke(Department.Rel... relations) {
            return new DepartmentRevokeAction(factory, id, relations);
        }
    }

    public static class DepartmentGrantAction extends TypedGrantAction<Department.Rel> {

        public DepartmentGrantAction(ResourceFactory factory, String id, Department.Rel... relations) {
            super(factory, id, relations);
        }

        public void toDepartment(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

    }

    public static class DepartmentRevokeAction extends TypedRevokeAction<Department.Rel> {

        public DepartmentRevokeAction(ResourceFactory factory, String id, Department.Rel... relations) {
            super(factory, id, relations);
        }

        public void fromDepartment(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

    }

}
