package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

// Generated by AuthxCodegen. Do not edit.
public final class DocNode {

    public static final Resource DocNode = new Resource();

    public static final class Resource extends ResourceType<Rel, Perm> {
        public final RelProxy Rel = new RelProxy();
        public final PermProxy Perm = new PermProxy();

        private Resource() {
            super("doc_node", com.authx.testapp.schema.DocNode.Rel::values, com.authx.testapp.schema.DocNode.Perm::values);
        }
    }

    public enum Rel implements Relation.Named {
        DEFAULT_EDITOR("default_editor", "org#member"),
        DEFAULT_MANAGER("default_manager", "org#member"),
        DEFAULT_READER("default_reader", "org#member"),
        EDITOR("editor", "user", "org#member"),
        ENTERPRISE_EDITOR("enterprise_editor", "org#member"),
        ENTERPRISE_MANAGER("enterprise_manager", "org#member"),
        ENTERPRISE_READER("enterprise_reader", "org#member"),
        MANAGER("manager", "user", "org#member"),
        OWNER("owner", "user"),
        PARENT("parent", "doc_node"),
        PUBLIC_EDITOR("public_editor", "user:*"),
        PUBLIC_MANAGER("public_manager", "user:*"),
        PUBLIC_READER("public_reader", "user:*"),
        READER("reader", "user", "org#member");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    public static final class RelProxy {
        public final Rel DEFAULT_EDITOR = Rel.DEFAULT_EDITOR;
        public final Rel DEFAULT_MANAGER = Rel.DEFAULT_MANAGER;
        public final Rel DEFAULT_READER = Rel.DEFAULT_READER;
        public final Rel EDITOR = Rel.EDITOR;
        public final Rel ENTERPRISE_EDITOR = Rel.ENTERPRISE_EDITOR;
        public final Rel ENTERPRISE_MANAGER = Rel.ENTERPRISE_MANAGER;
        public final Rel ENTERPRISE_READER = Rel.ENTERPRISE_READER;
        public final Rel MANAGER = Rel.MANAGER;
        public final Rel OWNER = Rel.OWNER;
        public final Rel PARENT = Rel.PARENT;
        public final Rel PUBLIC_EDITOR = Rel.PUBLIC_EDITOR;
        public final Rel PUBLIC_MANAGER = Rel.PUBLIC_MANAGER;
        public final Rel PUBLIC_READER = Rel.PUBLIC_READER;
        public final Rel READER = Rel.READER;
        private RelProxy() {}
    }

    public enum Perm implements Permission.Named {
        DIRECT_ASSIGNMENT("direct_assignment"),
        EDITOR_EFFECTIVE("editor_effective"),
        MANAGER_EFFECTIVE("manager_effective"),
        OWNER_EFFECTIVE("owner_effective"),
        READER_EFFECTIVE("reader_effective");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    public static final class PermProxy {
        public final Perm DIRECT_ASSIGNMENT = Perm.DIRECT_ASSIGNMENT;
        public final Perm EDITOR_EFFECTIVE = Perm.EDITOR_EFFECTIVE;
        public final Perm MANAGER_EFFECTIVE = Perm.MANAGER_EFFECTIVE;
        public final Perm OWNER_EFFECTIVE = Perm.OWNER_EFFECTIVE;
        public final Perm READER_EFFECTIVE = Perm.READER_EFFECTIVE;
        private PermProxy() {}
    }

    private DocNode() {}
}
