package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.testapp.schema.constants.Document;

/**
 * Typed resource facade for <b>document</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * DocumentResource doc = new DocumentResource(client);
 * doc.select("id").grant(Document.Rel.EDITOR).toUser("bob");
 * boolean ok = doc.select("id").check(Document.Perm.VIEW).by("alice");
 * </pre>
 */
public final class DocumentResource extends TypedResourceFactory<Document.Rel, Document.Perm> {

    public DocumentResource(AuthxClient client) {
        init("document", client);
    }
}
