package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

/**
 * Typed metadata for SpiceDB resource type <b>document</b>.
 * Generated by AuthxCodegen at 2026-04-21T12:40:14.579381Z — do not edit.
 *
 * <pre>
 * client.on(Document.TYPE).select(id).check(Document.Perm.VIEW).by(userId);
 * client.on(Document.TYPE).select(id).grant(Document.Rel.EDITOR).to(userId);
 * </pre>
 */
public final class Document {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter", "user", "group#member", "department#all_members"),
        EDITOR("editor", "user", "group#member", "department#all_members"),
        FOLDER("folder", "folder"),
        LINK_EDITOR("link_editor", "user:*"),
        LINK_VIEWER("link_viewer", "user:*"),
        OWNER("owner", "user"),
        SPACE("space", "space"),
        VIEWER("viewer", "user", "group#member", "department#all_members", "user:*");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        DELETE("delete"),
        EDIT("edit"),
        MANAGE("manage"),
        SHARE("share"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /** Typed descriptor — hand this to {@code client.on(...)}. */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("document", Rel.class, Perm.class);

    private Document() {}
}
