package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Typed metadata for SpiceDB resource type <b>document</b>.
 * Generated by AuthxCodegen at 2026-04-11T12:52:37.126647Z — do not edit.
 *
 * <p>This class is pure type metadata: two enums plus a
 * {@link ResourceType} constant. Every operation starts from
 * {@code client.on(Document.TYPE)}:
 *
 * <pre>
 * client.on(Document.TYPE).select(id).check(Document.Perm.VIEW).by(userId);
 * client.on(Document.TYPE).select(id).grant(Document.Rel.EDITOR).toUser(userId);
 * client.on(Document.TYPE).select(id).checkAll().by(userId);
 * client.on(Document.TYPE).findByUser(userId).limit(100).can(Document.Perm.VIEW);
 * </pre>
 */
public final class Document {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter"),
        EDITOR("editor"),
        FOLDER("folder"),
        LINK_EDITOR("link_editor"),
        LINK_VIEWER("link_viewer"),
        OWNER("owner"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        DELETE("delete"),
        EDIT("edit"),
        MANAGE("manage"),
        SHARE("share"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /**
     * Typed type descriptor. Hand this to {@code client.on(...)} to get
     * a chain that accepts only this type's {@link Rel} / {@link Perm} enums.
     */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("document", Rel.class, Perm.class);

    private Document() {}
}
