package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.ResourceFactory;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.testapp.schema.constants.Document;

/**
 * Type-safe resource factory for <b>document</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * DocumentResource doc = new DocumentResource(client);
 * doc.select("doc-1").grant(Document.Rel.EDITOR).toUser("bob");
 * doc.select("doc-1").grant(Document.Rel.EDITOR, Document.Rel.COMMENTER).toUser("bob");
 * doc.select("doc-1").check(Document.Perm.VIEW).by("alice");
 * doc.select("doc-1").revoke(Document.Rel.EDITOR).fromUser("bob");
 * </pre>
 */
public class DocumentResource extends TypedResourceFactory<Document.Rel, Document.Perm> {

    public DocumentResource(AuthxClient client) {
        init("document", client);
    }

    @Override
    public DocumentHandle select(String... ids) {
        return new DocumentHandle(this, ids);
    }

    public static class DocumentHandle extends TypedHandle<Document.Rel, Document.Perm> {

        public DocumentHandle(ResourceFactory factory, String[] ids) {
            super(factory, ids);
        }

        @Override @SuppressWarnings("unchecked")
        public DocumentGrantAction grant(Document.Rel... relations) {
            return new DocumentGrantAction(factory, ids, relations);
        }

        @Override @SuppressWarnings("unchecked")
        public DocumentRevokeAction revoke(Document.Rel... relations) {
            return new DocumentRevokeAction(factory, ids, relations);
        }
    }

    public static class DocumentGrantAction extends TypedGrantAction<Document.Rel> {

        public DocumentGrantAction(ResourceFactory factory, String[] ids, Document.Rel... relations) {
            super(factory, ids, relations);
        }

        public void toUser(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "user:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toUser(java.util.Collection<String> subjectIds) {
            toUser(subjectIds.toArray(String[]::new));
        }

        public void toGroupMember(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "group:" + subjectIds[i] + "#member";
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toGroupMember(java.util.Collection<String> subjectIds) {
            toGroupMember(subjectIds.toArray(String[]::new));
        }

        public void toDepartmentAllMembers(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "department:" + subjectIds[i] + "#all_members";
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toDepartmentAllMembers(java.util.Collection<String> subjectIds) {
            toDepartmentAllMembers(subjectIds.toArray(String[]::new));
        }

        public void toUserAll() {
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), "user:*");
        }

        public void toFolder(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "folder:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toFolder(java.util.Collection<String> subjectIds) {
            toFolder(subjectIds.toArray(String[]::new));
        }

        public void toSpace(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "space:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toSpace(java.util.Collection<String> subjectIds) {
            toSpace(subjectIds.toArray(String[]::new));
        }

    }

    public static class DocumentRevokeAction extends TypedRevokeAction<Document.Rel> {

        public DocumentRevokeAction(ResourceFactory factory, String[] ids, Document.Rel... relations) {
            super(factory, ids, relations);
        }

        public void fromUser(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "user:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromUser(java.util.Collection<String> subjectIds) {
            fromUser(subjectIds.toArray(String[]::new));
        }

        public void fromGroupMember(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "group:" + subjectIds[i] + "#member";
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromGroupMember(java.util.Collection<String> subjectIds) {
            fromGroupMember(subjectIds.toArray(String[]::new));
        }

        public void fromDepartmentAllMembers(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "department:" + subjectIds[i] + "#all_members";
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromDepartmentAllMembers(java.util.Collection<String> subjectIds) {
            fromDepartmentAllMembers(subjectIds.toArray(String[]::new));
        }

        public void fromUserAll() {
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), "user:*");
        }

        public void fromFolder(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "folder:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromFolder(java.util.Collection<String> subjectIds) {
            fromFolder(subjectIds.toArray(String[]::new));
        }

        public void fromSpace(String... subjectIds) {
            String[] refs = new String[subjectIds.length];
            for (int i = 0; i < subjectIds.length; i++) refs[i] = "space:" + subjectIds[i];
            for (var id : ids)
                for (var rel : relations)
                    factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromSpace(java.util.Collection<String> subjectIds) {
            fromSpace(subjectIds.toArray(String[]::new));
        }

    }

}
