package com.authx.testapp.schema;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

/**
 * Typed enums for SpiceDB resource type <b>document</b>.
 * Holds {@code Rel} + {@code Perm} enums used by the generated
 * {@code Schema.DocumentDescriptor} in Schema.java.
 * Generated by AuthxCodegen at 2026-04-22T03:37:29.783820Z — do not edit.
 */
public final class Document {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter", "user", "group#member", "department#all_members"),
        EDITOR("editor", "user", "group#member", "department#all_members"),
        FOLDER("folder", "folder"),
        LINK_EDITOR("link_editor", "user:*"),
        LINK_VIEWER("link_viewer", "user:*"),
        OWNER("owner", "user"),
        SPACE("space", "space"),
        VIEWER("viewer", "user", "group#member", "department#all_members", "user:*");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        DELETE("delete"),
        EDIT("edit"),
        MANAGE("manage"),
        SHARE("share"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Document() {}
}
