package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.sdk.model.GrantResult;
import com.authx.testapp.schema.constants.Document;

/**
 * Type-safe resource factory for <b>document</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * DocumentResource doc = client.document();
 * doc.grant("id", Document.Rel.EDITOR).toUser("bob");
 * doc.check("id", Document.Perm.VIEW, "alice");
 * </pre>
 */
public class DocumentResource extends TypedResourceFactory<Document.Rel, Document.Perm> {

    public DocumentResource(AuthxClient client) {
        init("document", client);
    }

    @Override
    public DocumentGrantAction grant(String id, Document.Rel relation) {
        return new DocumentGrantAction(this, id, relation);
    }

    @Override
    public DocumentRevokeAction revoke(String id, Document.Rel relation) {
        return new DocumentRevokeAction(this, id, relation);
    }

    /** Typed grant action with subject-specific to*() methods. */
    public static class DocumentGrantAction extends TypedGrantAction<Document.Rel> {

        public DocumentGrantAction(DocumentResource factory, String id, Document.Rel relation) {
            super(factory, id, relation);
        }

        /** Grant to user:{id}. */
        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to group:{id}#member. */
        public void toGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to department:{id}#all_members. */
        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to user:* (all). */
        public void toUserAll() {
            factory.grantToSubjects(id, relation.relationName(), "user:*");
        }

        /** Grant to folder:{id}. */
        public void toFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to space:{id}. */
        public void toSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

    }

    /** Typed revoke action with subject-specific from*() methods. */
    public static class DocumentRevokeAction extends TypedRevokeAction<Document.Rel> {

        public DocumentRevokeAction(DocumentResource factory, String id, Document.Rel relation) {
            super(factory, id, relation);
        }

        /** Revoke from user:{id}. */
        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from group:{id}#member. */
        public void fromGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from department:{id}#all_members. */
        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from user:* (all). */
        public void fromUserAll() {
            factory.revokeFromSubjects(id, relation.relationName(), "user:*");
        }

        /** Revoke from folder:{id}. */
        public void fromFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from space:{id}. */
        public void fromSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

    }

}
