package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.sdk.model.GrantResult;
import com.authx.testapp.schema.constants.Folder;

/**
 * Type-safe resource factory for <b>folder</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * FolderResource doc = client.folder();
 * doc.grant("id", Folder.Rel.EDITOR).toUser("bob");
 * doc.check("id", Folder.Perm.VIEW, "alice");
 * </pre>
 */
public class FolderResource extends TypedResourceFactory<Folder.Rel, Folder.Perm> {

    public FolderResource(AuthxClient client) {
        init("folder", client);
    }

    @Override
    public FolderGrantAction grant(String id, Folder.Rel relation) {
        return new FolderGrantAction(this, id, relation);
    }

    @Override
    public FolderRevokeAction revoke(String id, Folder.Rel relation) {
        return new FolderRevokeAction(this, id, relation);
    }

    /** Typed grant action with subject-specific to*() methods. */
    public static class FolderGrantAction extends TypedGrantAction<Folder.Rel> {

        public FolderGrantAction(FolderResource factory, String id, Folder.Rel relation) {
            super(factory, id, relation);
        }

        /** Grant to user:{id}. */
        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to folder:{id}. */
        public void toFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to group:{id}#member. */
        public void toGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to department:{id}#all_members. */
        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to user:* (all). */
        public void toUserAll() {
            factory.grantToSubjects(id, relation.relationName(), "user:*");
        }

        /** Grant to space:{id}. */
        public void toSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

    }

    /** Typed revoke action with subject-specific from*() methods. */
    public static class FolderRevokeAction extends TypedRevokeAction<Folder.Rel> {

        public FolderRevokeAction(FolderResource factory, String id, Folder.Rel relation) {
            super(factory, id, relation);
        }

        /** Revoke from user:{id}. */
        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from folder:{id}. */
        public void fromFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from group:{id}#member. */
        public void fromGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from department:{id}#all_members. */
        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from user:* (all). */
        public void fromUserAll() {
            factory.revokeFromSubjects(id, relation.relationName(), "user:*");
        }

        /** Revoke from space:{id}. */
        public void fromSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

    }

}
