package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

/**
 * Typed metadata for SpiceDB resource type <b>folder</b>.
 * Generated by AuthxCodegen at 2026-04-21T12:50:24.042171Z — do not edit.
 *
 * <pre>
 * client.on(Folder.TYPE).select(id).check(Folder.Perm.VIEW).by(userId);
 * client.on(Folder.TYPE).select(id).grant(Folder.Rel.EDITOR).to(userId);
 * </pre>
 */
public final class Folder {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter", "user", "group#member", "department#all_members"),
        EDITOR("editor", "user", "group#member", "department#all_members"),
        OWNER("owner", "user"),
        PARENT("parent", "folder"),
        SPACE("space", "space"),
        VIEWER("viewer", "user", "group#member", "department#all_members", "user:*");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        CREATE_CHILD("create_child"),
        EDIT("edit"),
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /** Typed descriptor — hand this to {@code client.on(...)}. */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("folder", Rel.class, Perm.class);

    private Folder() {}
}
