package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.ResourceFactory;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.testapp.schema.constants.Folder;

/**
 * Type-safe resource factory for <b>folder</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * FolderResource doc = new FolderResource(client);
 * doc.on("doc-1").grant(Folder.Rel.EDITOR).toUser("bob");
 * doc.on("doc-1").grant(Folder.Rel.EDITOR, Folder.Rel.COMMENTER).toUser("bob");
 * doc.on("doc-1").check(Folder.Perm.VIEW).by("alice");
 * doc.on("doc-1").revoke(Folder.Rel.EDITOR).fromUser("bob");
 * </pre>
 */
public class FolderResource extends TypedResourceFactory<Folder.Rel, Folder.Perm> {

    public FolderResource(AuthxClient client) {
        init("folder", client);
    }

    @Override
    public FolderHandle select(String id) {
        return new FolderHandle(this, id);
    }

    public static class FolderHandle extends TypedHandle<Folder.Rel, Folder.Perm> {

        public FolderHandle(ResourceFactory factory, String id) {
            super(factory, id);
        }

        @Override @SuppressWarnings("unchecked")
        public FolderGrantAction grant(Folder.Rel... relations) {
            return new FolderGrantAction(factory, id, relations);
        }

        @Override @SuppressWarnings("unchecked")
        public FolderRevokeAction revoke(Folder.Rel... relations) {
            return new FolderRevokeAction(factory, id, relations);
        }
    }

    public static class FolderGrantAction extends TypedGrantAction<Folder.Rel> {

        public FolderGrantAction(ResourceFactory factory, String id, Folder.Rel... relations) {
            super(factory, id, relations);
        }

        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toUserAll() {
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), "user:*");
        }

        public void toSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

    }

    public static class FolderRevokeAction extends TypedRevokeAction<Folder.Rel> {

        public FolderRevokeAction(ResourceFactory factory, String id, Folder.Rel... relations) {
            super(factory, id, relations);
        }

        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromFolder(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "folder:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromUserAll() {
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), "user:*");
        }

        public void fromSpace(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "space:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

    }

}
