package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.testapp.schema.constants.Folder;

/**
 * Typed resource facade for <b>folder</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * FolderResource doc = new FolderResource(client);
 * doc.select("id").grant(Folder.Rel.EDITOR).toUser("bob");
 * boolean ok = doc.select("id").check(Folder.Perm.VIEW).by("alice");
 * </pre>
 */
public final class FolderResource extends TypedResourceFactory<Folder.Rel, Folder.Perm> {

    public FolderResource(AuthxClient client) {
        init("folder", client);
    }
}
