package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Typed metadata for SpiceDB resource type <b>folder</b>.
 * Generated by AuthxCodegen at 2026-04-11T12:52:37.130733Z — do not edit.
 *
 * <p>This class is pure type metadata: two enums plus a
 * {@link ResourceType} constant. Every operation starts from
 * {@code client.on(Folder.TYPE)}:
 *
 * <pre>
 * client.on(Folder.TYPE).select(id).check(Folder.Perm.VIEW).by(userId);
 * client.on(Folder.TYPE).select(id).grant(Folder.Rel.EDITOR).toUser(userId);
 * client.on(Folder.TYPE).select(id).checkAll().by(userId);
 * client.on(Folder.TYPE).findByUser(userId).limit(100).can(Folder.Perm.VIEW);
 * </pre>
 */
public final class Folder {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        ANCESTOR("ancestor"),
        COMMENTER("commenter"),
        EDITOR("editor"),
        OWNER("owner"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        COMMENT_LOCAL("comment_local"),
        CREATE_CHILD("create_child"),
        EDIT("edit"),
        EDIT_LOCAL("edit_local"),
        MANAGE("manage"),
        MANAGE_LOCAL("manage_local"),
        VIEW("view"),
        VIEW_LOCAL("view_local");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /**
     * Typed type descriptor. Hand this to {@code client.on(...)} to get
     * a chain that accepts only this type's {@link Rel} / {@link Perm} enums.
     */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("folder", Rel.class, Perm.class);

    private Folder() {}
}
