package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

/**
 * Typed metadata for SpiceDB resource type <b>group</b>.
 * Generated by AuthxCodegen at 2026-04-21T12:01:52.087687Z — do not edit.
 *
 * <pre>
 * client.on(Group.TYPE).select(id).check(Group.Perm.VIEW).by(userId);
 * client.on(Group.TYPE).select(id).grant(Group.Rel.EDITOR).to(userId);
 * </pre>
 */
public final class Group {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        MEMBER("member", "user", "department#all_members");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        ;

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /** Typed descriptor — hand this to {@code client.on(...)}. */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("group", Rel.class, Perm.class);

    private Group() {}
}
