package com.authx.testapp.schema;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

/**
 * Typed enums for SpiceDB resource type <b>group</b>.
 * Holds {@code Rel} + {@code Perm} enums used by the generated
 * {@code Schema.GroupDescriptor} in Schema.java.
 * Generated by AuthxCodegen at 2026-04-22T03:37:29.780196Z — do not edit.
 */
public final class Group {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        MEMBER("member", "user", "department#all_members");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        ;

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Group() {}
}
