package com.authx.testapp.schema;

import com.authx.sdk.model.CaveatRef;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Typed caveat <b>ip_allowlist</b>.
 * <p>IP allow-list — 只有来源 IP 落在 cidrs 列表中任一 CIDR 时权限才生效。
 * <p>CEL: {@code cidrs.exists(c, client_ip.startsWith(c))}
 * Generated by AuthxCodegen — do not edit.
 */
public final class IpAllowlist {

    public static final String NAME = "ip_allowlist";

    /** Parameter {@code client_ip} — expected type: {@code String} */
    public static final String CLIENT_IP = "client_ip";

    /** Parameter {@code cidrs} — expected type: {@code List&lt;String&gt;} */
    public static final String CIDRS = "cidrs";

    /** Build a {@link CaveatRef} for grant-time binding. */
    public static CaveatRef ref(Object... keyValues) {
        return new CaveatRef(NAME, toMap(keyValues));
    }

    /** Build a context map for check-time evaluation. */
    public static Map<String, Object> context(Object... keyValues) {
        return toMap(keyValues);
    }

    private static Map<String, Object> toMap(Object... kv) {
        if (kv.length % 2 != 0) {
            throw new IllegalArgumentException(
                    "keyValues must have even length (alternating key, value pairs)");
        }
        var map = new LinkedHashMap<String, Object>();
        for (int i = 0; i < kv.length; i += 2) {
            if (!(kv[i] instanceof String)) {
                throw new IllegalArgumentException(
                        "Key at index " + i + " must be a String, got: " + kv[i].getClass().getName());
            }
            map.put((String) kv[i], kv[i + 1]);
        }
        return map;
    }

    private IpAllowlist() {}
}
