package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

// Generated by AuthxCodegen. Do not edit.
public final class Org {

    public static final Resource Org = new Resource();

    public static final class Resource extends ResourceType<Rel, Perm> {
        public final RelProxy Rel = new RelProxy();
        public final PermProxy Perm = new PermProxy();

        private Resource() {
            super("org", com.authx.testapp.schema.Org.Rel::values, com.authx.testapp.schema.Org.Perm::values);
        }
    }

    public enum Rel implements Relation.Named {
        MEMBER("member", "user");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    public static final class RelProxy {
        public final Rel MEMBER = Rel.MEMBER;
        private RelProxy() {}
    }

    public enum Perm implements Permission.Named {
        ;

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    public static final class PermProxy {
        private PermProxy() {}
    }

    private Org() {}
}
