package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Typed metadata for SpiceDB resource type <b>organization</b>.
 * Generated by AuthxCodegen at 2026-04-11T12:52:37.114585Z — do not edit.
 *
 * <p>This class is pure type metadata: two enums plus a
 * {@link ResourceType} constant. Every operation starts from
 * {@code client.on(Organization.TYPE)}:
 *
 * <pre>
 * client.on(Organization.TYPE).select(id).check(Organization.Perm.VIEW).by(userId);
 * client.on(Organization.TYPE).select(id).grant(Organization.Rel.EDITOR).toUser(userId);
 * client.on(Organization.TYPE).select(id).checkAll().by(userId);
 * client.on(Organization.TYPE).findByUser(userId).limit(100).can(Organization.Perm.VIEW);
 * </pre>
 */
public final class Organization {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        ACCESS("access"),
        MANAGE("manage");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /**
     * Typed type descriptor. Hand this to {@code client.on(...)} to get
     * a chain that accepts only this type's {@link Rel} / {@link Perm} enums.
     */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("organization", Rel.class, Perm.class);

    private Organization() {}
}
