package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.sdk.model.GrantResult;
import com.authx.testapp.schema.constants.Organization;

/**
 * Type-safe resource factory for <b>organization</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * OrganizationResource doc = client.organization();
 * doc.grant("id", Organization.Rel.EDITOR).toUser("bob");
 * doc.check("id", Organization.Perm.VIEW, "alice");
 * </pre>
 */
public class OrganizationResource extends TypedResourceFactory<Organization.Rel, Organization.Perm> {

    public OrganizationResource(AuthxClient client) {
        init("organization", client);
    }

    @Override
    public OrganizationGrantAction grant(String id, Organization.Rel relation) {
        return new OrganizationGrantAction(this, id, relation);
    }

    @Override
    public OrganizationRevokeAction revoke(String id, Organization.Rel relation) {
        return new OrganizationRevokeAction(this, id, relation);
    }

    /** Typed grant action with subject-specific to*() methods. */
    public static class OrganizationGrantAction extends TypedGrantAction<Organization.Rel> {

        public OrganizationGrantAction(OrganizationResource factory, String id, Organization.Rel relation) {
            super(factory, id, relation);
        }

        /** Grant to user:{id}. */
        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to department:{id}#all_members. */
        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

    }

    /** Typed revoke action with subject-specific from*() methods. */
    public static class OrganizationRevokeAction extends TypedRevokeAction<Organization.Rel> {

        public OrganizationRevokeAction(OrganizationResource factory, String id, Organization.Rel relation) {
            super(factory, id, relation);
        }

        /** Revoke from user:{id}. */
        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from department:{id}#all_members. */
        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

    }

}
