package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;
import com.authx.sdk.model.SubjectType;

import java.util.Arrays;
import java.util.List;

// Generated by AuthxCodegen. Do not edit.
public final class Project {

    public static final Resource Project = new Resource();

    public static final class Resource extends ResourceType<Rel, Perm> {
        public final RelProxy Rel = new RelProxy();
        public final PermProxy Perm = new PermProxy();

        private Resource() {
            super("project", com.authx.testapp.schema.Project.Rel::values, com.authx.testapp.schema.Project.Perm::values);
        }
    }

    public enum Rel implements Relation.Named {
        MANAGER("manager", "user", "org#member"),
        MEMBER("member", "user", "org#member"),
        OWNER("owner", "user");

        private final String value;
        private final List<SubjectType> subjectTypes;
        Rel(String v, String... sts) {
            this.value = v;
            this.subjectTypes = Arrays.stream(sts).map(SubjectType::parse).toList();
        }
        @Override public String relationName() { return value; }
        @Override public List<SubjectType> subjectTypes() { return subjectTypes; }
    }

    public static final class RelProxy {
        public final Rel MANAGER = Rel.MANAGER;
        public final Rel MEMBER = Rel.MEMBER;
        public final Rel OWNER = Rel.OWNER;
        private RelProxy() {}
    }

    public enum Perm implements Permission.Named {
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    public static final class PermProxy {
        public final Perm MANAGE = Perm.MANAGE;
        public final Perm VIEW = Perm.VIEW;
        private PermProxy() {}
    }

    private Project() {}
}
