package com.authx.testapp.schema;

/**
 * SpiceDB resource type constants.
 * Use these instead of hardcoded strings in {@code client.resource(type, id)}.
 * Generated by AuthxCodegen — do not edit.
 */
public final class ResourceTypes {

    public static final String USER = "user";
    public static final String GROUP = "group";
    public static final String SPACE = "space";
    public static final String ORGANIZATION = "organization";
    public static final String DOCUMENT = "document";
    public static final String DEPARTMENT = "department";
    public static final String FOLDER = "folder";

    private ResourceTypes() {}
}
