package com.authx.testapp.schema;

/**
 * Canonical resource type names from the SpiceDB schema.
 * Use these constants when you need a dynamic (string) resource type.
 * Generated by AuthxCodegen — do not edit.
 */
public final class ResourceTypes {

    public static final String DEPARTMENT = "department";
    public static final String DOCUMENT = "document";
    public static final String FOLDER = "folder";
    public static final String GROUP = "group";
    public static final String ORGANIZATION = "organization";
    public static final String SPACE = "space";
    public static final String USER = "user";

    private ResourceTypes() {}
}
