package com.authx.testapp.schema;

import com.authx.sdk.PermissionProxy;
import com.authx.sdk.ResourceType;

/**
 * Flat descriptor aggregator — business code does {@code import static com.authx.testapp.schema.Schema.*} to bring {@code Organization}, {@code User},
 * etc. into scope as typed descriptor values (NOT enum container classes).
 * Generated by AuthxCodegen at 2026-04-22T03:37:29.786923Z — do not edit.
 *
 * <pre>
 * import static com.authx.testapp.schema.Schema.*;
 * client.on(Document).select(docId).check(Document.Perm.VIEW).by(User, userId);
 * </pre>
 */
public final class Schema {

    private Schema() {}

    public static final class DepartmentDescriptor
            extends ResourceType<com.authx.testapp.schema.Department.Rel, com.authx.testapp.schema.Department.Perm> {
        protected DepartmentDescriptor() {
            super("department", com.authx.testapp.schema.Department.Rel.class, com.authx.testapp.schema.Department.Perm.class);
        }
        public final DepartmentRelProxy  Rel  = new DepartmentRelProxy();
        public final DepartmentPermProxy Perm = new DepartmentPermProxy();
    }

    public static final class DepartmentRelProxy {
        public final com.authx.testapp.schema.Department.Rel MEMBER = com.authx.testapp.schema.Department.Rel.MEMBER;
        public final com.authx.testapp.schema.Department.Rel PARENT = com.authx.testapp.schema.Department.Rel.PARENT;
    }

    public static final class DepartmentPermProxy implements PermissionProxy<com.authx.testapp.schema.Department.Perm> {
        public final com.authx.testapp.schema.Department.Perm ALL_MEMBERS = com.authx.testapp.schema.Department.Perm.ALL_MEMBERS;
        @Override public Class<com.authx.testapp.schema.Department.Perm> enumClass() {
            return com.authx.testapp.schema.Department.Perm.class;
        }
    }

    public static final DepartmentDescriptor Department = new DepartmentDescriptor();

    public static final class DocumentDescriptor
            extends ResourceType<com.authx.testapp.schema.Document.Rel, com.authx.testapp.schema.Document.Perm> {
        protected DocumentDescriptor() {
            super("document", com.authx.testapp.schema.Document.Rel.class, com.authx.testapp.schema.Document.Perm.class);
        }
        public final DocumentRelProxy  Rel  = new DocumentRelProxy();
        public final DocumentPermProxy Perm = new DocumentPermProxy();
    }

    public static final class DocumentRelProxy {
        public final com.authx.testapp.schema.Document.Rel COMMENTER = com.authx.testapp.schema.Document.Rel.COMMENTER;
        public final com.authx.testapp.schema.Document.Rel EDITOR = com.authx.testapp.schema.Document.Rel.EDITOR;
        public final com.authx.testapp.schema.Document.Rel FOLDER = com.authx.testapp.schema.Document.Rel.FOLDER;
        public final com.authx.testapp.schema.Document.Rel LINK_EDITOR = com.authx.testapp.schema.Document.Rel.LINK_EDITOR;
        public final com.authx.testapp.schema.Document.Rel LINK_VIEWER = com.authx.testapp.schema.Document.Rel.LINK_VIEWER;
        public final com.authx.testapp.schema.Document.Rel OWNER = com.authx.testapp.schema.Document.Rel.OWNER;
        public final com.authx.testapp.schema.Document.Rel SPACE = com.authx.testapp.schema.Document.Rel.SPACE;
        public final com.authx.testapp.schema.Document.Rel VIEWER = com.authx.testapp.schema.Document.Rel.VIEWER;
    }

    public static final class DocumentPermProxy implements PermissionProxy<com.authx.testapp.schema.Document.Perm> {
        public final com.authx.testapp.schema.Document.Perm COMMENT = com.authx.testapp.schema.Document.Perm.COMMENT;
        public final com.authx.testapp.schema.Document.Perm DELETE = com.authx.testapp.schema.Document.Perm.DELETE;
        public final com.authx.testapp.schema.Document.Perm EDIT = com.authx.testapp.schema.Document.Perm.EDIT;
        public final com.authx.testapp.schema.Document.Perm MANAGE = com.authx.testapp.schema.Document.Perm.MANAGE;
        public final com.authx.testapp.schema.Document.Perm SHARE = com.authx.testapp.schema.Document.Perm.SHARE;
        public final com.authx.testapp.schema.Document.Perm VIEW = com.authx.testapp.schema.Document.Perm.VIEW;
        @Override public Class<com.authx.testapp.schema.Document.Perm> enumClass() {
            return com.authx.testapp.schema.Document.Perm.class;
        }
    }

    public static final DocumentDescriptor Document = new DocumentDescriptor();

    public static final class FolderDescriptor
            extends ResourceType<com.authx.testapp.schema.Folder.Rel, com.authx.testapp.schema.Folder.Perm> {
        protected FolderDescriptor() {
            super("folder", com.authx.testapp.schema.Folder.Rel.class, com.authx.testapp.schema.Folder.Perm.class);
        }
        public final FolderRelProxy  Rel  = new FolderRelProxy();
        public final FolderPermProxy Perm = new FolderPermProxy();
    }

    public static final class FolderRelProxy {
        public final com.authx.testapp.schema.Folder.Rel COMMENTER = com.authx.testapp.schema.Folder.Rel.COMMENTER;
        public final com.authx.testapp.schema.Folder.Rel EDITOR = com.authx.testapp.schema.Folder.Rel.EDITOR;
        public final com.authx.testapp.schema.Folder.Rel OWNER = com.authx.testapp.schema.Folder.Rel.OWNER;
        public final com.authx.testapp.schema.Folder.Rel PARENT = com.authx.testapp.schema.Folder.Rel.PARENT;
        public final com.authx.testapp.schema.Folder.Rel SPACE = com.authx.testapp.schema.Folder.Rel.SPACE;
        public final com.authx.testapp.schema.Folder.Rel VIEWER = com.authx.testapp.schema.Folder.Rel.VIEWER;
    }

    public static final class FolderPermProxy implements PermissionProxy<com.authx.testapp.schema.Folder.Perm> {
        public final com.authx.testapp.schema.Folder.Perm COMMENT = com.authx.testapp.schema.Folder.Perm.COMMENT;
        public final com.authx.testapp.schema.Folder.Perm CREATE_CHILD = com.authx.testapp.schema.Folder.Perm.CREATE_CHILD;
        public final com.authx.testapp.schema.Folder.Perm EDIT = com.authx.testapp.schema.Folder.Perm.EDIT;
        public final com.authx.testapp.schema.Folder.Perm MANAGE = com.authx.testapp.schema.Folder.Perm.MANAGE;
        public final com.authx.testapp.schema.Folder.Perm VIEW = com.authx.testapp.schema.Folder.Perm.VIEW;
        @Override public Class<com.authx.testapp.schema.Folder.Perm> enumClass() {
            return com.authx.testapp.schema.Folder.Perm.class;
        }
    }

    public static final FolderDescriptor Folder = new FolderDescriptor();

    public static final class GroupDescriptor
            extends ResourceType<com.authx.testapp.schema.Group.Rel, com.authx.testapp.schema.Group.Perm> {
        protected GroupDescriptor() {
            super("group", com.authx.testapp.schema.Group.Rel.class, com.authx.testapp.schema.Group.Perm.class);
        }
        public final GroupRelProxy  Rel  = new GroupRelProxy();
        public final GroupPermProxy Perm = new GroupPermProxy();
    }

    public static final class GroupRelProxy {
        public final com.authx.testapp.schema.Group.Rel MEMBER = com.authx.testapp.schema.Group.Rel.MEMBER;
    }

    public static final class GroupPermProxy implements PermissionProxy<com.authx.testapp.schema.Group.Perm> {
        @Override public Class<com.authx.testapp.schema.Group.Perm> enumClass() {
            return com.authx.testapp.schema.Group.Perm.class;
        }
    }

    public static final GroupDescriptor Group = new GroupDescriptor();

    public static final class OrganizationDescriptor
            extends ResourceType<com.authx.testapp.schema.Organization.Rel, com.authx.testapp.schema.Organization.Perm> {
        protected OrganizationDescriptor() {
            super("organization", com.authx.testapp.schema.Organization.Rel.class, com.authx.testapp.schema.Organization.Perm.class);
        }
        public final OrganizationRelProxy  Rel  = new OrganizationRelProxy();
        public final OrganizationPermProxy Perm = new OrganizationPermProxy();
    }

    public static final class OrganizationRelProxy {
        public final com.authx.testapp.schema.Organization.Rel ADMIN = com.authx.testapp.schema.Organization.Rel.ADMIN;
        public final com.authx.testapp.schema.Organization.Rel MEMBER = com.authx.testapp.schema.Organization.Rel.MEMBER;
    }

    public static final class OrganizationPermProxy implements PermissionProxy<com.authx.testapp.schema.Organization.Perm> {
        public final com.authx.testapp.schema.Organization.Perm ACCESS = com.authx.testapp.schema.Organization.Perm.ACCESS;
        public final com.authx.testapp.schema.Organization.Perm MANAGE = com.authx.testapp.schema.Organization.Perm.MANAGE;
        @Override public Class<com.authx.testapp.schema.Organization.Perm> enumClass() {
            return com.authx.testapp.schema.Organization.Perm.class;
        }
    }

    public static final OrganizationDescriptor Organization = new OrganizationDescriptor();

    public static final class SpaceDescriptor
            extends ResourceType<com.authx.testapp.schema.Space.Rel, com.authx.testapp.schema.Space.Perm> {
        protected SpaceDescriptor() {
            super("space", com.authx.testapp.schema.Space.Rel.class, com.authx.testapp.schema.Space.Perm.class);
        }
        public final SpaceRelProxy  Rel  = new SpaceRelProxy();
        public final SpacePermProxy Perm = new SpacePermProxy();
    }

    public static final class SpaceRelProxy {
        public final com.authx.testapp.schema.Space.Rel ADMIN = com.authx.testapp.schema.Space.Rel.ADMIN;
        public final com.authx.testapp.schema.Space.Rel MEMBER = com.authx.testapp.schema.Space.Rel.MEMBER;
        public final com.authx.testapp.schema.Space.Rel ORG = com.authx.testapp.schema.Space.Rel.ORG;
        public final com.authx.testapp.schema.Space.Rel OWNER = com.authx.testapp.schema.Space.Rel.OWNER;
        public final com.authx.testapp.schema.Space.Rel VIEWER = com.authx.testapp.schema.Space.Rel.VIEWER;
    }

    public static final class SpacePermProxy implements PermissionProxy<com.authx.testapp.schema.Space.Perm> {
        public final com.authx.testapp.schema.Space.Perm EDIT = com.authx.testapp.schema.Space.Perm.EDIT;
        public final com.authx.testapp.schema.Space.Perm MANAGE = com.authx.testapp.schema.Space.Perm.MANAGE;
        public final com.authx.testapp.schema.Space.Perm VIEW = com.authx.testapp.schema.Space.Perm.VIEW;
        @Override public Class<com.authx.testapp.schema.Space.Perm> enumClass() {
            return com.authx.testapp.schema.Space.Perm.class;
        }
    }

    public static final SpaceDescriptor Space = new SpaceDescriptor();

    public static final class UserDescriptor
            extends ResourceType<com.authx.testapp.schema.User.Rel, com.authx.testapp.schema.User.Perm> {
        protected UserDescriptor() {
            super("user", com.authx.testapp.schema.User.Rel.class, com.authx.testapp.schema.User.Perm.class);
        }
        public final UserRelProxy  Rel  = new UserRelProxy();
        public final UserPermProxy Perm = new UserPermProxy();
    }

    public static final class UserRelProxy {
    }

    public static final class UserPermProxy implements PermissionProxy<com.authx.testapp.schema.User.Perm> {
        @Override public Class<com.authx.testapp.schema.User.Perm> enumClass() {
            return com.authx.testapp.schema.User.Perm.class;
        }
    }

    public static final UserDescriptor User = new UserDescriptor();

}
