package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.sdk.model.GrantResult;
import com.authx.testapp.schema.constants.Space;

/**
 * Type-safe resource factory for <b>space</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * SpaceResource doc = client.space();
 * doc.grant("id", Space.Rel.EDITOR).toUser("bob");
 * doc.check("id", Space.Perm.VIEW, "alice");
 * </pre>
 */
public class SpaceResource extends TypedResourceFactory<Space.Rel, Space.Perm> {

    public SpaceResource(AuthxClient client) {
        init("space", client);
    }

    @Override
    public SpaceGrantAction grant(String id, Space.Rel relation) {
        return new SpaceGrantAction(this, id, relation);
    }

    @Override
    public SpaceRevokeAction revoke(String id, Space.Rel relation) {
        return new SpaceRevokeAction(this, id, relation);
    }

    /** Typed grant action with subject-specific to*() methods. */
    public static class SpaceGrantAction extends TypedGrantAction<Space.Rel> {

        public SpaceGrantAction(SpaceResource factory, String id, Space.Rel relation) {
            super(factory, id, relation);
        }

        /** Grant to user:{id}. */
        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to group:{id}#member. */
        public void toGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to department:{id}#all_members. */
        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

        /** Grant to user:* (all). */
        public void toUserAll() {
            factory.grantToSubjects(id, relation.relationName(), "user:*");
        }

        /** Grant to organization:{id}. */
        public void toOrganization(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "organization:" + ids[i] + "";
            factory.grantToSubjects(id, relation.relationName(), refs);
        }

    }

    /** Typed revoke action with subject-specific from*() methods. */
    public static class SpaceRevokeAction extends TypedRevokeAction<Space.Rel> {

        public SpaceRevokeAction(SpaceResource factory, String id, Space.Rel relation) {
            super(factory, id, relation);
        }

        /** Revoke from user:{id}. */
        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from group:{id}#member. */
        public void fromGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from department:{id}#all_members. */
        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

        /** Revoke from user:* (all). */
        public void fromUserAll() {
            factory.revokeFromSubjects(id, relation.relationName(), "user:*");
        }

        /** Revoke from organization:{id}. */
        public void fromOrganization(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "organization:" + ids[i] + "";
            factory.revokeFromSubjects(id, relation.relationName(), refs);
        }

    }

}
