package com.authx.testapp.schema;

import com.authx.sdk.ResourceType;
import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Typed metadata for SpiceDB resource type <b>space</b>.
 * Generated by AuthxCodegen at 2026-04-11T12:52:37.131487Z — do not edit.
 *
 * <p>This class is pure type metadata: two enums plus a
 * {@link ResourceType} constant. Every operation starts from
 * {@code client.on(Space.TYPE)}:
 *
 * <pre>
 * client.on(Space.TYPE).select(id).check(Space.Perm.VIEW).by(userId);
 * client.on(Space.TYPE).select(id).grant(Space.Rel.EDITOR).toUser(userId);
 * client.on(Space.TYPE).select(id).checkAll().by(userId);
 * client.on(Space.TYPE).findByUser(userId).limit(100).can(Space.Perm.VIEW);
 * </pre>
 */
public final class Space {

    /** Relations — used with grant / revoke on the typed chain. */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member"),
        ORG("org"),
        OWNER("owner"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with check / who / findBy on the typed chain. */
    public enum Perm implements Permission.Named {
        EDIT("edit"),
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    /**
     * Typed type descriptor. Hand this to {@code client.on(...)} to get
     * a chain that accepts only this type's {@link Rel} / {@link Perm} enums.
     */
    public static final ResourceType<Rel, Perm> TYPE =
            ResourceType.of("space", Rel.class, Perm.class);

    private Space() {}
}
