package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.ResourceFactory;
import com.authx.sdk.TypedResourceFactory;
import com.authx.sdk.TypedGrantAction;
import com.authx.sdk.TypedRevokeAction;
import com.authx.testapp.schema.constants.Space;

/**
 * Type-safe resource factory for <b>space</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * SpaceResource doc = new SpaceResource(client);
 * doc.on("doc-1").grant(Space.Rel.EDITOR).toUser("bob");
 * doc.on("doc-1").grant(Space.Rel.EDITOR, Space.Rel.COMMENTER).toUser("bob");
 * doc.on("doc-1").check(Space.Perm.VIEW).by("alice");
 * doc.on("doc-1").revoke(Space.Rel.EDITOR).fromUser("bob");
 * </pre>
 */
public class SpaceResource extends TypedResourceFactory<Space.Rel, Space.Perm> {

    public SpaceResource(AuthxClient client) {
        init("space", client);
    }

    @Override
    public SpaceHandle select(String id) {
        return new SpaceHandle(this, id);
    }

    public static class SpaceHandle extends TypedHandle<Space.Rel, Space.Perm> {

        public SpaceHandle(ResourceFactory factory, String id) {
            super(factory, id);
        }

        @Override @SuppressWarnings("unchecked")
        public SpaceGrantAction grant(Space.Rel... relations) {
            return new SpaceGrantAction(factory, id, relations);
        }

        @Override @SuppressWarnings("unchecked")
        public SpaceRevokeAction revoke(Space.Rel... relations) {
            return new SpaceRevokeAction(factory, id, relations);
        }
    }

    public static class SpaceGrantAction extends TypedGrantAction<Space.Rel> {

        public SpaceGrantAction(ResourceFactory factory, String id, Space.Rel... relations) {
            super(factory, id, relations);
        }

        public void toUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

        public void toUserAll() {
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), "user:*");
        }

        public void toOrganization(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "organization:" + ids[i];
            for (var rel : relations) factory.grantToSubjects(id, rel.relationName(), refs);
        }

    }

    public static class SpaceRevokeAction extends TypedRevokeAction<Space.Rel> {

        public SpaceRevokeAction(ResourceFactory factory, String id, Space.Rel... relations) {
            super(factory, id, relations);
        }

        public void fromUser(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "user:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromGroupMember(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "group:" + ids[i] + "#member";
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromDepartmentAllMembers(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "department:" + ids[i] + "#all_members";
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

        public void fromUserAll() {
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), "user:*");
        }

        public void fromOrganization(String... ids) {
            String[] refs = new String[ids.length];
            for (int i = 0; i < ids.length; i++) refs[i] = "organization:" + ids[i];
            for (var rel : relations) factory.revokeFromSubjects(id, rel.relationName(), refs);
        }

    }

}
