package com.authx.testapp.schema;

import com.authx.sdk.AuthxClient;
import com.authx.sdk.TypedResourceFactory;
import com.authx.testapp.schema.constants.Space;

/**
 * Typed resource facade for <b>space</b>.
 * Generated by AuthxCodegen — do not edit.
 *
 * <pre>
 * SpaceResource doc = new SpaceResource(client);
 * doc.select("id").grant(Space.Rel.EDITOR).toUser("bob");
 * boolean ok = doc.select("id").check(Space.Perm.VIEW).by("alice");
 * </pre>
 */
public final class SpaceResource extends TypedResourceFactory<Space.Rel, Space.Perm> {

    public SpaceResource(AuthxClient client) {
        init("space", client);
    }
}
