package com.authcses.testapp.schema.constants;

import com.authcses.sdk.model.Permission;
import com.authcses.sdk.model.Relation;

/**
 * Type-safe enums for the <b>folder</b> definition.
 * Generated by AuthCsesCodegen at 2026-04-07T04:26:05.338140Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Folder.Rel.EDITOR, "bob");
 * doc.check("doc-1", Folder.Perm.VIEW, "alice");
 * </pre>
 */
public final class Folder {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter"),
        EDITOR("editor"),
        OWNER("owner"),
        PARENT("parent"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions (used in check / lookup / who). */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        CREATE_CHILD("create_child"),
        EDIT("edit"),
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Folder() {}
}
