package com.authcses.testapp.schema.constants;

import com.authcses.sdk.model.Permission;
import com.authcses.sdk.model.Relation;

/**
 * Type-safe enums for the <b>group</b> definition.
 * Generated by AuthCsesCodegen at 2026-04-07T04:26:05.335746Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Group.Rel.EDITOR, "bob");
 * doc.check("doc-1", Group.Perm.VIEW, "alice");
 * </pre>
 */
public final class Group {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        MEMBER("member");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    private Group() {}
}
