package com.authx.sdk;

import com.authx.sdk.cache.SchemaCache;
import com.authx.sdk.model.SubjectType;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class AuthxCodegenTest {

    @Test
    void emitsRelEnumWithSubjectTypesVarargs() {
        String code = AuthxCodegen.emitTypeClass(
                "document",
                Set.of("folder", "viewer"),
                Set.of("view"),
                Map.of(
                        "folder", List.of(SubjectType.of("folder")),
                        "viewer", List.of(
                                SubjectType.of("user"),
                                SubjectType.of("group", "member"),
                                SubjectType.wildcard("user"))),
                "com.example.perm");

        assertThat(code).contains("package com.example.perm;");
        assertThat(code).contains("import com.authx.sdk.ResourceType;");
        assertThat(code).contains("import com.authx.sdk.model.SubjectType;");
        assertThat(code).contains("public final class Document");
        assertThat(code).contains("public static final Resource Document = new Resource();");
        assertThat(code).contains("public static final class Resource extends ResourceType<Rel, Perm>");
        assertThat(code).contains("public final RelProxy Rel = new RelProxy();");
        assertThat(code).contains("public final PermProxy Perm = new PermProxy();");
        assertThat(code).contains("super(\"document\", com.example.perm.Document.Rel::values, com.example.perm.Document.Perm::values);");
        assertThat(code).contains("FOLDER(\"folder\", \"folder\")");
        assertThat(code).contains("VIEWER(\"viewer\", \"user\", \"group#member\", \"user:*\")");
        assertThat(code).contains("public final Rel VIEWER = Rel.VIEWER;");
        assertThat(code).contains("public final Perm VIEW = Perm.VIEW;");
        assertThat(code).contains("Rel(String v, String... sts)");
        assertThat(code).contains("Arrays.stream(sts).map(SubjectType::parse).toList()");
        assertThat(code).contains("public List<SubjectType> subjectTypes()");
        assertThat(code).contains("VIEW(\"view\")");
        assertThat(code).doesNotContain("TYPE");
        assertThat(code).doesNotContain("Generated by AuthxCodegen at ");
        assertThat(code).contains("// Generated by AuthxCodegen. Do not edit.");
        assertThat(code).contains("public enum Rel implements Relation.Named");
        assertThat(code).contains("public enum Perm implements Permission.Named");
    }

    @Test
    void emittedTypeClassCarriesSameNameDescriptor() {
        String code = AuthxCodegen.emitTypeClass(
                "project",
                Set.of("member"),
                Set.of("view"),
                Map.of("member", List.of(SubjectType.of("user"))),
                "com.example.perm");

        assertThat(code).contains("public final class Project");
        assertThat(code).contains("public static final Resource Project = new Resource();");
        assertThat(code).contains("public final Rel MEMBER = Rel.MEMBER;");
        assertThat(code).contains("public final Perm VIEW = Perm.VIEW;");
        assertThat(code).doesNotContain("Schema");
        assertThat(code).doesNotContain("TYPE");
    }

    @Test
    void emitsCaveatClass() {
        String code = AuthxCodegen.emitCaveatClass(
                "ip_allowlist",
                Map.of("cidrs", "list<string>", "client_ip", "string"),
                "client_ip in cidrs",
                "IP allow-list",
                "com.example.perm");
        assertThat(code).contains("public static final String NAME = \"ip_allowlist\";");
        assertThat(code).contains("public static final String CIDRS = \"cidrs\";");
        assertThat(code).contains("public static final String CLIENT_IP = \"client_ip\";");
        assertThat(code).contains("public static CaveatRef ref(Object... keyValues)");
        assertThat(code).contains("public static Map<String, Object> context(Object... keyValues)");
    }

    @Test
    void endToEndFromFakeSchema(@org.junit.jupiter.api.io.TempDir Path tmp) throws Exception {
        SchemaCache cache = new SchemaCache();
        cache.updateFromMap(Map.of(
                "document", new SchemaCache.DefinitionCache(
                        Set.of("folder", "viewer"),
                        Set.of("view"),
                        Map.of(
                                "folder", List.of(SubjectType.of("folder")),
                                "viewer", List.of(
                                        SubjectType.of("user"),
                                        SubjectType.wildcard("user"))))));
        cache.updateCaveats(Map.of(
                "ip_allowlist", new SchemaCache.CaveatDef(
                        "ip_allowlist",
                        Map.of("cidrs", "list<string>"),
                        "client_ip in cidrs",
                        "")));
        SchemaClient schema = new SchemaClient(cache);

        AuthxCodegen.generate(schema, tmp.toString(), "com.example.perm");

        Path docFile     = tmp.resolve("com/example/perm/Document.java");
        Path rtFile      = tmp.resolve("com/example/perm/ResourceTypes.java");
        Path schemaFile  = tmp.resolve("com/example/perm/Schema.java");
        Path ipFile      = tmp.resolve("com/example/perm/IpAllowlist.java");
        Path caveatsFile = tmp.resolve("com/example/perm/Caveats.java");
        assertThat(Files.exists(docFile)).isTrue();
        assertThat(Files.exists(rtFile)).isFalse();      // no longer emitted (T018)
        assertThat(Files.exists(schemaFile)).isFalse();
        assertThat(Files.exists(ipFile)).isTrue();
        assertThat(Files.exists(caveatsFile)).isTrue();

        String doc = Files.readString(docFile);
        assertThat(doc).contains("// Generated by AuthxCodegen. Do not edit.");
        assertThat(doc).contains("public static final Resource Document = new Resource();");
        assertThat(doc).contains("FOLDER(\"folder\", \"folder\")");
    }

    @Test
    void generateRemovesObsoleteResourceTypesFileIfPresent(
            @org.junit.jupiter.api.io.TempDir Path tmp) throws Exception {
        // Pre-create a stale ResourceTypes.java from a previous codegen run
        Path pkgDir = tmp.resolve("com/example/perm");
        Files.createDirectories(pkgDir);
        Path staleFile = pkgDir.resolve("ResourceTypes.java");
        Files.writeString(staleFile,
                "package com.example.perm; public final class ResourceTypes {}");
        assertThat(Files.exists(staleFile)).isTrue();

        SchemaCache cache = new SchemaCache();
        cache.updateFromMap(Map.of(
                "document", new SchemaCache.DefinitionCache(
                        Set.of("viewer"),
                        Set.of("view"),
                        Map.of("viewer", List.of(SubjectType.of("user"))))));
        SchemaClient schema = new SchemaClient(cache);

        AuthxCodegen.generate(schema, tmp.toString(), "com.example.perm");

        assertThat(Files.exists(staleFile)).isFalse();
        assertThat(Files.exists(pkgDir.resolve("Schema.java"))).isFalse();
    }
}
