global:
  scrape_interval: 10s

scrape_configs:
  - job_name: spicedb
    static_configs:
      - targets:
          - "host.docker.internal:9090"
          - "host.docker.internal:9091"
        labels:
          cluster: spicedb

  - job_name: cockroachdb
    metrics_path: /_status/vars
    static_configs:
      - targets:
          - "host.docker.internal:8080"
          - "host.docker.internal:8081"
          - "host.docker.internal:8082"
        labels:
          cluster: cockroachdb

  - job_name: cluster-test
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8091"
          - "host.docker.internal:8092"
          - "host.docker.internal:8093"
        labels:
          cluster: app
