package com.authx.sdk;

import com.authx.sdk.cache.SchemaCache;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Code generator: reads schema from a live AuthxClient and generates
 * type-safe Java constant classes into the caller's project.
 *
 * <pre>
 * var client = AuthxClient.builder()
 *     .connection(c -> c.target("localhost:50051").presharedKey("dev-token"))
 *     .build();
 *
 * AuthxCodegen.generate(client, "src/main/java", "com.mycompany.permissions");
 * client.close();
 * </pre>
 *
 * Generates:
 * <ul>
 *   <li>{@code com/mycompany/permissions/constants/Document.java} — relation + permission constants</li>
 *   <li>{@code com/mycompany/permissions/constants/Folder.java}</li>
 *   <li>{@code com/mycompany/permissions/Subjects.java} — subject factory methods</li>
 * </ul>
 */
public final class AuthxCodegen {

    private static final System.Logger LOG = System.getLogger(AuthxCodegen.class.getName());

    private AuthxCodegen() {}

    /**
     * Generate type-safe constant classes from the client's schema.
     *
     * @param client      a connected AuthxClient (schema must be loaded)
     * @param outputDir   root source directory (e.g., "src/main/java")
     * @param packageName target package (e.g., "com.mycompany.permissions")
     */
    public static void generate(AuthxClient client, String outputDir, String packageName) throws IOException {
        var schema = client.schema();
        if (!schema.isLoaded()) {
            throw new IllegalStateException("Schema not loaded. Ensure the client connected to SpiceDB successfully.");
        }

        String constantsPkg = packageName + ".constants";
        Path constantsDir = Path.of(outputDir, constantsPkg.replace('.', '/'));
        Files.createDirectories(constantsDir);

        Set<String> types = schema.resourceTypes();
        LOG.log(System.Logger.Level.INFO, "AuthxCodegen: generating for " + types.size() + " resource types");

        Path basePkgDir = Path.of(outputDir, packageName.replace('.', '/'));
        Files.createDirectories(basePkgDir);

        for (String type : types) {
            Set<String> relations = schema.relationsOf(type);
            Set<String> permissions = schema.permissionsOf(type);
            if (relations.isEmpty() && permissions.isEmpty()) continue;

            // 1. Enum constants
            String code = generateConstantClass(type, relations, permissions, constantsPkg);
            Path file = constantsDir.resolve(toPascalCase(type) + ".java");
            Files.writeString(file, code);
            LOG.log(System.Logger.Level.INFO, "  Generated: " + file);

            // 2. Typed resource factory (only for types with both relations AND permissions)
            if (!relations.isEmpty() && !permissions.isEmpty()) {
                var subjectTypes = schema.allSubjectTypes(type);
                String resourceCode = generateTypedResource(type, relations, permissions, subjectTypes, packageName, constantsPkg);
                Path resourceFile = basePkgDir.resolve(toPascalCase(type) + "Resource.java");
                Files.writeString(resourceFile, resourceCode);
                LOG.log(System.Logger.Level.INFO, "  Generated: " + resourceFile);
            }
        }

        // Subjects factory
        Path subjectsFile = basePkgDir.resolve("Subjects.java");
        Files.writeString(subjectsFile, generateSubjectsFactory(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + subjectsFile);

        // ResourceTypes constant class
        Path resourceTypesFile = basePkgDir.resolve("ResourceTypes.java");
        Files.writeString(resourceTypesFile, generateResourceTypes(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + resourceTypesFile);

        LOG.log(System.Logger.Level.INFO, "AuthxCodegen: done.");
    }

    static String generateConstantClass(String typeName, Set<String> relations,
                                        Set<String> permissions, String packageName) {
        String className = toPascalCase(typeName);
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import com.authx.sdk.model.Permission;\n");
        sb.append("import com.authx.sdk.model.Relation;\n\n");
        sb.append("/**\n");
        sb.append(" * Type-safe enums for the <b>").append(typeName).append("</b> definition.\n");
        sb.append(" * Generated by AuthxCodegen at ").append(Instant.now()).append(" — do not edit.\n");
        sb.append(" *\n");
        sb.append(" * <pre>\n");
        sb.append(" * // Compile-time safe:\n");
        sb.append(" * doc.grant(\"doc-1\", ").append(className).append(".Rel.EDITOR, \"bob\");\n");
        sb.append(" * doc.check(\"doc-1\", ").append(className).append(".Perm.VIEW, \"alice\");\n");
        sb.append(" * </pre>\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");

        // Relation enum
        if (!relations.isEmpty()) {
            sb.append("    /** Relations (used in grant / revoke). */\n");
            sb.append("    public enum Rel implements Relation.Named {\n");
            var relList = relations.stream().sorted().toList();
            for (int i = 0; i < relList.size(); i++) {
                String rel = relList.get(i);
                sb.append("        ").append(toConstant(rel)).append("(\"").append(rel).append("\")");
                sb.append(i < relList.size() - 1 ? ",\n" : ";\n");
            }
            sb.append("\n        private final String value;\n");
            sb.append("        Rel(String v) { this.value = v; }\n");
            sb.append("        @Override public String relationName() { return value; }\n");
            sb.append("    }\n\n");
        }

        // Permission enum
        if (!permissions.isEmpty()) {
            sb.append("    /** Permissions (used in check / lookup / who). */\n");
            sb.append("    public enum Perm implements Permission.Named {\n");
            var permList = permissions.stream().sorted().toList();
            for (int i = 0; i < permList.size(); i++) {
                String perm = permList.get(i);
                sb.append("        ").append(toConstant(perm)).append("(\"").append(perm).append("\")");
                sb.append(i < permList.size() - 1 ? ",\n" : ";\n");
            }
            sb.append("\n        private final String value;\n");
            sb.append("        Perm(String v) { this.value = v; }\n");
            sb.append("        @Override public String permissionName() { return value; }\n");
            sb.append("    }\n\n");
        }

        sb.append("    private ").append(className).append("() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    /**
     * Generate a typed resource factory class with 3-segment chain:
     *   doc.on("id").grant(Rel...).toUser("bob")
     *   doc.on("id").check(Perm).by("alice")
     *   doc.on("id").revoke(Rel...).fromUser("bob")
     */
    static String generateTypedResource(String typeName, Set<String> relations, Set<String> permissions,
                                         Map<String, List<SchemaCache.SubjectType>> subjectTypes,
                                         String packageName, String constantsPkg) {
        String className = toPascalCase(typeName) + "Resource";
        String enumClass = constantsPkg + "." + toPascalCase(typeName);
        String E = toPascalCase(typeName); // e.g., "Document"

        // Collect all unique subject types across all relations
        Set<String> allSubjectKeys = new LinkedHashSet<>();
        for (var entry : subjectTypes.entrySet()) {
            for (var st : entry.getValue()) {
                allSubjectKeys.add(subjectKey(st));
            }
        }

        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import com.authx.sdk.AuthxClient;\n");
        sb.append("import com.authx.sdk.ResourceFactory;\n");
        sb.append("import com.authx.sdk.TypedResourceFactory;\n");
        sb.append("import com.authx.sdk.TypedGrantAction;\n");
        sb.append("import com.authx.sdk.TypedRevokeAction;\n");
        sb.append("import ").append(enumClass).append(";\n\n");

        sb.append("/**\n");
        sb.append(" * Type-safe resource factory for <b>").append(typeName).append("</b>.\n");
        sb.append(" * Generated by AuthxCodegen — do not edit.\n");
        sb.append(" *\n");
        sb.append(" * <pre>\n");
        sb.append(" * ").append(className).append(" doc = new ").append(className).append("(client);\n");
        sb.append(" * doc.on(\"doc-1\").grant(").append(E).append(".Rel.EDITOR).toUser(\"bob\");\n");
        sb.append(" * doc.on(\"doc-1\").grant(").append(E).append(".Rel.EDITOR, ").append(E).append(".Rel.COMMENTER).toUser(\"bob\");\n");
        sb.append(" * doc.on(\"doc-1\").check(").append(E).append(".Perm.VIEW).by(\"alice\");\n");
        sb.append(" * doc.on(\"doc-1\").revoke(").append(E).append(".Rel.EDITOR).fromUser(\"bob\");\n");
        sb.append(" * </pre>\n");
        sb.append(" */\n");
        sb.append("public class ").append(className)
                .append(" extends TypedResourceFactory<").append(E).append(".Rel, ").append(E).append(".Perm> {\n\n");

        // Constructor
        sb.append("    public ").append(className).append("(AuthxClient client) {\n");
        sb.append("        init(\"").append(typeName).append("\", client);\n");
        sb.append("    }\n\n");

        // Override on() → typed handle
        sb.append("    @Override\n");
        sb.append("    public ").append(E).append("Handle on(String id) {\n");
        sb.append("        return new ").append(E).append("Handle(this, id);\n");
        sb.append("    }\n\n");

        // ---- Handle: on("id") → .grant() / .check() / .revoke() ----
        sb.append("    public static class ").append(E)
                .append("Handle extends TypedHandle<").append(E).append(".Rel, ").append(E).append(".Perm> {\n\n");
        sb.append("        public ").append(E).append("Handle(ResourceFactory factory, String id) {\n");
        sb.append("            super(factory, id);\n");
        sb.append("        }\n\n");
        // grant returns typed action
        sb.append("        @Override @SuppressWarnings(\"unchecked\")\n");
        sb.append("        public ").append(E).append("GrantAction grant(").append(E).append(".Rel... relations) {\n");
        sb.append("            return new ").append(E).append("GrantAction(factory, id, relations);\n");
        sb.append("        }\n\n");
        // revoke returns typed action
        sb.append("        @Override @SuppressWarnings(\"unchecked\")\n");
        sb.append("        public ").append(E).append("RevokeAction revoke(").append(E).append(".Rel... relations) {\n");
        sb.append("            return new ").append(E).append("RevokeAction(factory, id, relations);\n");
        sb.append("        }\n");
        sb.append("    }\n\n");

        // ---- GrantAction with to* methods ----
        sb.append("    public static class ").append(E)
                .append("GrantAction extends TypedGrantAction<").append(E).append(".Rel> {\n\n");
        sb.append("        public ").append(E).append("GrantAction(ResourceFactory factory, String id, ").append(E).append(".Rel... relations) {\n");
        sb.append("            super(factory, id, relations);\n");
        sb.append("        }\n\n");

        for (String key : allSubjectKeys) {
            var parts = parseSubjectKey(key);
            generateToMethod(sb, parts, "to", "grantToSubjects");
        }
        sb.append("    }\n\n");

        // ---- RevokeAction with from* methods ----
        sb.append("    public static class ").append(E)
                .append("RevokeAction extends TypedRevokeAction<").append(E).append(".Rel> {\n\n");
        sb.append("        public ").append(E).append("RevokeAction(ResourceFactory factory, String id, ").append(E).append(".Rel... relations) {\n");
        sb.append("            super(factory, id, relations);\n");
        sb.append("        }\n\n");

        for (String key : allSubjectKeys) {
            var parts = parseSubjectKey(key);
            generateToMethod(sb, parts, "from", "revokeFromSubjects");
        }
        sb.append("    }\n\n");

        sb.append("}\n");
        return sb.toString();
    }

    /** Generate a to* or from* method in the grant/revoke action class. */
    private static void generateToMethod(StringBuilder sb, SubjectParts parts,
                                          String prefix, String factoryMethod) {
        String methodName = prefix + toPascalCase(parts.type)
                + (parts.wildcard ? "All" : (parts.relation.isEmpty() ? "" : toPascalCase(parts.relation)));

        if (parts.wildcard) {
            sb.append("        public void ").append(methodName).append("() {\n");
            sb.append("            for (var rel : relations) factory.").append(factoryMethod)
                    .append("(id, rel.relationName(), \"").append(parts.type).append(":*\");\n");
            sb.append("        }\n\n");
        } else {
            String refExpr = parts.relation.isEmpty()
                    ? "\"" + parts.type + ":\" + ids[i]"
                    : "\"" + parts.type + ":\" + ids[i] + \"#" + parts.relation + "\"";
            sb.append("        public void ").append(methodName).append("(String... ids) {\n");
            sb.append("            String[] refs = new String[ids.length];\n");
            sb.append("            for (int i = 0; i < ids.length; i++) refs[i] = ").append(refExpr).append(";\n");
            sb.append("            for (var rel : relations) factory.").append(factoryMethod)
                    .append("(id, rel.relationName(), refs);\n");
            sb.append("        }\n\n");
        }
    }

    // ---- Subject type helpers for codegen ----

    private record SubjectParts(String type, String relation, boolean wildcard) {}

    private static String subjectKey(SchemaCache.SubjectType st) {
        if (st.isWildcard()) return st.type() + ":*";
        if (st.optionalRelation() != null && !st.optionalRelation().isEmpty())
            return st.type() + "#" + st.optionalRelation();
        return st.type();
    }

    private static SubjectParts parseSubjectKey(String key) {
        if (key.endsWith(":*")) return new SubjectParts(key.replace(":*", ""), "", true);
        if (key.contains("#")) {
            var split = key.split("#", 2);
            return new SubjectParts(split[0], split[1], false);
        }
        return new SubjectParts(key, "", false);
    }

    /** e.g., "user" → "toUser", "department#all_members" → "toDepartmentAllMembers", "user:*" → "toUserAll" */
    private static String toMethodName(SubjectParts parts) {
        String base = "to" + toPascalCase(parts.type);
        if (parts.wildcard) return base + "All";
        if (!parts.relation.isEmpty()) return base + toPascalCase(parts.relation);
        return base;
    }

    /** e.g., "user:{id}", "department:{id}#all_members", "user:*" */
    private static String toRefTemplate(SubjectParts parts) {
        if (parts.wildcard) return parts.type + ":*";
        if (!parts.relation.isEmpty()) return parts.type + ":{id}#" + parts.relation;
        return parts.type + ":{id}";
    }

    static String generateResourceTypes(String packageName, Set<String> allTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * SpiceDB resource type constants.\n");
        sb.append(" * Use these instead of hardcoded strings in {@code client.resource(type, id)}.\n");
        sb.append(" * Generated by AuthxCodegen — do not edit.\n */\n");
        sb.append("public final class ResourceTypes {\n\n");
        for (String type : allTypes) {
            sb.append("    public static final String ").append(toConstant(type))
                    .append(" = \"").append(type).append("\";\n");
        }
        sb.append("\n    private ResourceTypes() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String generateSubjectsFactory(String packageName, Set<String> resourceTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * Subject reference factory.\n");
        sb.append(" * Generated by AuthxCodegen — do not edit.\n */\n");
        sb.append("public final class Subjects {\n\n");

        for (String type : resourceTypes) {
            String method = toCamelCase(type);
            sb.append("    public static String ").append(method).append("(String id) {\n");
            sb.append("        return \"").append(type).append(":\" + id;\n");
            sb.append("    }\n\n");
        }

        sb.append("    private Subjects() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String toPascalCase(String snake) {
        return Arrays.stream(snake.split("[_-]"))
                .map(s -> s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1))
                .collect(Collectors.joining());
    }

    static String toCamelCase(String snake) {
        String pascal = toPascalCase(snake);
        return pascal.isEmpty() ? pascal : Character.toLowerCase(pascal.charAt(0)) + pascal.substring(1);
    }

    static String toConstant(String name) {
        // snake_case → UPPER_SNAKE: "can_view" → "CAN_VIEW"
        // camelCase → UPPER_SNAKE: "canView" → "CAN_VIEW"
        return name.replaceAll("([a-z])([A-Z])", "$1_$2").toUpperCase();
    }
}
