package com.authx.sdk;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Code generator: reads schema from a live AuthxClient and generates
 * type-safe Java constant classes into the caller's project.
 *
 * <pre>
 * var client = AuthxClient.builder()
 *     .connection(c -> c.target("localhost:50051").presharedKey("dev-token"))
 *     .build();
 *
 * AuthxCodegen.generate(client, "src/main/java", "com.mycompany.permissions");
 * client.close();
 * </pre>
 *
 * Generates:
 * <ul>
 *   <li>{@code com/mycompany/permissions/constants/Document.java} — relation + permission constants</li>
 *   <li>{@code com/mycompany/permissions/constants/Folder.java}</li>
 *   <li>{@code com/mycompany/permissions/Subjects.java} — subject factory methods</li>
 * </ul>
 */
public final class AuthxCodegen {

    private static final System.Logger LOG = System.getLogger(AuthxCodegen.class.getName());

    private AuthxCodegen() {}

    /**
     * Generate type-safe constant classes from the client's schema.
     *
     * @param client      a connected AuthxClient (schema must be loaded)
     * @param outputDir   root source directory (e.g., "src/main/java")
     * @param packageName target package (e.g., "com.mycompany.permissions")
     */
    public static void generate(AuthxClient client, String outputDir, String packageName) throws IOException {
        var schema = client.schema();
        if (!schema.isLoaded()) {
            throw new IllegalStateException("Schema not loaded. Ensure the client connected to SpiceDB successfully.");
        }

        String constantsPkg = packageName + ".constants";
        Path constantsDir = Path.of(outputDir, constantsPkg.replace('.', '/'));
        Files.createDirectories(constantsDir);

        Set<String> types = schema.resourceTypes();
        LOG.log(System.Logger.Level.INFO, "AuthxCodegen: generating for " + types.size() + " resource types");

        for (String type : types) {
            Set<String> relations = schema.relationsOf(type);
            Set<String> permissions = schema.permissionsOf(type);
            if (relations.isEmpty() && permissions.isEmpty()) continue;

            String code = generateConstantClass(type, relations, permissions, constantsPkg);
            Path file = constantsDir.resolve(toPascalCase(type) + ".java");
            Files.writeString(file, code);
            LOG.log(System.Logger.Level.INFO, "  Generated: " + file);
        }

        // Subjects factory
        Path subjectsFile = Path.of(outputDir, packageName.replace('.', '/'), "Subjects.java");
        Files.createDirectories(subjectsFile.getParent());
        Files.writeString(subjectsFile, generateSubjectsFactory(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + subjectsFile);

        // ResourceTypes constant class
        Path resourceTypesFile = Path.of(outputDir, packageName.replace('.', '/'), "ResourceTypes.java");
        Files.writeString(resourceTypesFile, generateResourceTypes(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + resourceTypesFile);

        LOG.log(System.Logger.Level.INFO, "AuthxCodegen: done.");
    }

    static String generateConstantClass(String typeName, Set<String> relations,
                                        Set<String> permissions, String packageName) {
        String className = toPascalCase(typeName);
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import com.authx.sdk.model.Permission;\n");
        sb.append("import com.authx.sdk.model.Relation;\n\n");
        sb.append("/**\n");
        sb.append(" * Type-safe enums for the <b>").append(typeName).append("</b> definition.\n");
        sb.append(" * Generated by AuthxCodegen at ").append(Instant.now()).append(" — do not edit.\n");
        sb.append(" *\n");
        sb.append(" * <pre>\n");
        sb.append(" * // Compile-time safe:\n");
        sb.append(" * doc.grant(\"doc-1\", ").append(className).append(".Rel.EDITOR, \"bob\");\n");
        sb.append(" * doc.check(\"doc-1\", ").append(className).append(".Perm.VIEW, \"alice\");\n");
        sb.append(" * </pre>\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");

        // Relation enum
        if (!relations.isEmpty()) {
            sb.append("    /** Relations (used in grant / revoke). */\n");
            sb.append("    public enum Rel implements Relation.Named {\n");
            var relList = relations.stream().sorted().toList();
            for (int i = 0; i < relList.size(); i++) {
                String rel = relList.get(i);
                sb.append("        ").append(toConstant(rel)).append("(\"").append(rel).append("\")");
                sb.append(i < relList.size() - 1 ? ",\n" : ";\n");
            }
            sb.append("\n        private final String value;\n");
            sb.append("        Rel(String v) { this.value = v; }\n");
            sb.append("        @Override public String relationName() { return value; }\n");
            sb.append("    }\n\n");
        }

        // Permission enum
        if (!permissions.isEmpty()) {
            sb.append("    /** Permissions (used in check / lookup / who). */\n");
            sb.append("    public enum Perm implements Permission.Named {\n");
            var permList = permissions.stream().sorted().toList();
            for (int i = 0; i < permList.size(); i++) {
                String perm = permList.get(i);
                sb.append("        ").append(toConstant(perm)).append("(\"").append(perm).append("\")");
                sb.append(i < permList.size() - 1 ? ",\n" : ";\n");
            }
            sb.append("\n        private final String value;\n");
            sb.append("        Perm(String v) { this.value = v; }\n");
            sb.append("        @Override public String permissionName() { return value; }\n");
            sb.append("    }\n\n");
        }

        sb.append("    private ").append(className).append("() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String generateResourceTypes(String packageName, Set<String> allTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * SpiceDB resource type constants.\n");
        sb.append(" * Use these instead of hardcoded strings in {@code client.resource(type, id)}.\n");
        sb.append(" * Generated by AuthxCodegen — do not edit.\n */\n");
        sb.append("public final class ResourceTypes {\n\n");
        for (String type : allTypes) {
            sb.append("    public static final String ").append(toConstant(type))
                    .append(" = \"").append(type).append("\";\n");
        }
        sb.append("\n    private ResourceTypes() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String generateSubjectsFactory(String packageName, Set<String> resourceTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * Subject reference factory.\n");
        sb.append(" * Generated by AuthxCodegen — do not edit.\n */\n");
        sb.append("public final class Subjects {\n\n");

        for (String type : resourceTypes) {
            String method = toCamelCase(type);
            sb.append("    public static String ").append(method).append("(String id) {\n");
            sb.append("        return \"").append(type).append(":\" + id;\n");
            sb.append("    }\n\n");
        }

        sb.append("    private Subjects() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String toPascalCase(String snake) {
        return Arrays.stream(snake.split("[_-]"))
                .map(s -> s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1))
                .collect(Collectors.joining());
    }

    static String toCamelCase(String snake) {
        String pascal = toPascalCase(snake);
        return pascal.isEmpty() ? pascal : Character.toLowerCase(pascal.charAt(0)) + pascal.substring(1);
    }

    static String toConstant(String name) {
        // snake_case → UPPER_SNAKE: "can_view" → "CAN_VIEW"
        // camelCase → UPPER_SNAKE: "canView" → "CAN_VIEW"
        return name.replaceAll("([a-z])([A-Z])", "$1_$2").toUpperCase();
    }
}
