package com.authcses.sdk;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Code generator: reads schema from a live AuthCsesClient and generates
 * type-safe Java constant classes into the caller's project.
 *
 * <pre>
 * var client = AuthCsesClient.builder()
 *     .target("localhost:50051")
 *     .presharedKey("dev-token")
 *     .build();
 *
 * AuthCsesCodegen.generate(client, "src/main/java", "com.mycompany.permissions");
 * client.close();
 * </pre>
 *
 * Generates:
 * <ul>
 *   <li>{@code com/mycompany/permissions/constants/Document.java} — relation + permission constants</li>
 *   <li>{@code com/mycompany/permissions/constants/Folder.java}</li>
 *   <li>{@code com/mycompany/permissions/Subjects.java} — subject factory methods</li>
 * </ul>
 */
public final class AuthCsesCodegen {

    private static final System.Logger LOG = System.getLogger(AuthCsesCodegen.class.getName());

    private AuthCsesCodegen() {}

    /**
     * Generate type-safe constant classes from the client's schema.
     *
     * @param client      a connected AuthCsesClient (schema must be loaded)
     * @param outputDir   root source directory (e.g., "src/main/java")
     * @param packageName target package (e.g., "com.mycompany.permissions")
     */
    public static void generate(AuthCsesClient client, String outputDir, String packageName) throws IOException {
        var schema = client.schema();
        if (!schema.isLoaded()) {
            throw new IllegalStateException("Schema not loaded. Ensure the client connected to SpiceDB successfully.");
        }

        String constantsPkg = packageName + ".constants";
        Path constantsDir = Path.of(outputDir, constantsPkg.replace('.', '/'));
        Files.createDirectories(constantsDir);

        Set<String> types = schema.resourceTypes();
        LOG.log(System.Logger.Level.INFO, "AuthCsesCodegen: generating for " + types.size() + " resource types");

        for (String type : types) {
            Set<String> relations = schema.relationsOf(type);
            Set<String> permissions = schema.permissionsOf(type);
            if (relations.isEmpty() && permissions.isEmpty()) continue;

            String code = generateConstantClass(type, relations, permissions, constantsPkg);
            Path file = constantsDir.resolve(toPascalCase(type) + ".java");
            Files.writeString(file, code);
            LOG.log(System.Logger.Level.INFO, "  Generated: " + file);
        }

        // Subjects factory
        Path subjectsFile = Path.of(outputDir, packageName.replace('.', '/'), "Subjects.java");
        Files.createDirectories(subjectsFile.getParent());
        Files.writeString(subjectsFile, generateSubjectsFactory(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + subjectsFile);

        // ResourceTypes constant class
        Path resourceTypesFile = Path.of(outputDir, packageName.replace('.', '/'), "ResourceTypes.java");
        Files.writeString(resourceTypesFile, generateResourceTypes(packageName, types));
        LOG.log(System.Logger.Level.INFO, "  Generated: " + resourceTypesFile);

        LOG.log(System.Logger.Level.INFO, "AuthCsesCodegen: done.");
    }

    static String generateConstantClass(String typeName, Set<String> relations,
                                        Set<String> permissions, String packageName) {
        String className = toPascalCase(typeName);
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n");
        sb.append(" * Constants for the <b>").append(typeName).append("</b> definition.\n");
        sb.append(" * Generated by AuthCsesCodegen at ").append(Instant.now()).append(" — do not edit.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");

        if (!relations.isEmpty()) {
            sb.append("    // ---- Relations (grant / revoke / relations) ----\n");
            for (String rel : relations) {
                sb.append("    public static final String ").append(toConstant(rel))
                        .append(" = \"").append(rel).append("\";\n");
            }
            sb.append("\n");
        }

        if (!permissions.isEmpty()) {
            sb.append("    // ---- Permissions (check / who / lookup) ----\n");
            for (String perm : permissions) {
                sb.append("    public static final String ").append(toConstant(perm))
                        .append(" = \"").append(perm).append("\";\n");
            }
            sb.append("\n");
        }

        if (!relations.isEmpty()) {
            sb.append("    public static final String[] ALL_RELATIONS = { ")
                    .append(relations.stream().map(r -> "\"" + r + "\"").collect(Collectors.joining(", ")))
                    .append(" };\n");
        }
        if (!permissions.isEmpty()) {
            sb.append("    public static final String[] ALL_PERMISSIONS = { ")
                    .append(permissions.stream().map(p -> "\"" + p + "\"").collect(Collectors.joining(", ")))
                    .append(" };\n");
        }

        sb.append("\n    private ").append(className).append("() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String generateResourceTypes(String packageName, Set<String> allTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * SpiceDB resource type constants.\n");
        sb.append(" * Use these instead of hardcoded strings in {@code client.resource(type, id)}.\n");
        sb.append(" * Generated by AuthCsesCodegen — do not edit.\n */\n");
        sb.append("public final class ResourceTypes {\n\n");
        for (String type : allTypes) {
            sb.append("    public static final String ").append(toConstant(type))
                    .append(" = \"").append(type).append("\";\n");
        }
        sb.append("\n    private ResourceTypes() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String generateSubjectsFactory(String packageName, Set<String> resourceTypes) {
        var sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n * Subject reference factory.\n");
        sb.append(" * Generated by AuthCsesCodegen — do not edit.\n */\n");
        sb.append("public final class Subjects {\n\n");

        for (String type : resourceTypes) {
            String method = toCamelCase(type);
            sb.append("    public static String ").append(method).append("(String id) {\n");
            sb.append("        return \"").append(type).append(":\" + id;\n");
            sb.append("    }\n\n");
        }

        sb.append("    private Subjects() {}\n");
        sb.append("}\n");
        return sb.toString();
    }

    static String toPascalCase(String snake) {
        return Arrays.stream(snake.split("[_-]"))
                .map(s -> s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1))
                .collect(Collectors.joining());
    }

    static String toCamelCase(String snake) {
        String pascal = toPascalCase(snake);
        return pascal.isEmpty() ? pascal : Character.toLowerCase(pascal.charAt(0)) + pascal.substring(1);
    }

    static String toConstant(String name) {
        // snake_case → UPPER_SNAKE: "can_view" → "CAN_VIEW"
        // camelCase → UPPER_SNAKE: "canView" → "CAN_VIEW"
        return name.replaceAll("([a-z])([A-Z])", "$1_$2").toUpperCase();
    }
}
