package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Type-safe enums for the <b>department</b> definition.
 * Generated by AuthxCodegen at 2026-04-07T07:05:29.649847Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Department.Rel.EDITOR, "bob");
 * doc.check("doc-1", Department.Perm.VIEW, "alice");
 * </pre>
 */
public final class Department {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        MEMBER("member"),
        PARENT("parent");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions (used in check / lookup / who). */
    public enum Perm implements Permission.Named {
        ALL_MEMBERS("all_members");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Department() {}
}
