package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Type-safe enums for the <b>document</b> definition.
 * Generated by AuthxCodegen at 2026-04-07T04:26:05.337381Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Document.Rel.EDITOR, "bob");
 * doc.check("doc-1", Document.Perm.VIEW, "alice");
 * </pre>
 */
public final class Document {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter"),
        EDITOR("editor"),
        FOLDER("folder"),
        LINK_EDITOR("link_editor"),
        LINK_VIEWER("link_viewer"),
        OWNER("owner"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions (used in check / lookup / who). */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        DELETE("delete"),
        EDIT("edit"),
        MANAGE("manage"),
        SHARE("share"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Document() {}
}
