package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Canonical relation and permission names for <b>document</b>.
 * Generated by AuthxCodegen at 2026-04-11T08:58:02.603338Z — do not edit.
 */
public final class Document {

    /** Relations — used with TypedHandle.grant / revoke. */
    public enum Rel implements Relation.Named {
        COMMENTER("commenter"),
        EDITOR("editor"),
        FOLDER("folder"),
        LINK_EDITOR("link_editor"),
        LINK_VIEWER("link_viewer"),
        OWNER("owner"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with TypedHandle.check / who / findBy. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        DELETE("delete"),
        EDIT("edit"),
        MANAGE("manage"),
        SHARE("share"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Document() {}
}
