package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Canonical relation and permission names for <b>folder</b>.
 * Generated by AuthxCodegen at 2026-04-11T08:58:02.600914Z — do not edit.
 */
public final class Folder {

    /** Relations — used with TypedHandle.grant / revoke. */
    public enum Rel implements Relation.Named {
        ANCESTOR("ancestor"),
        COMMENTER("commenter"),
        EDITOR("editor"),
        OWNER("owner"),
        SPACE("space"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with TypedHandle.check / who / findBy. */
    public enum Perm implements Permission.Named {
        COMMENT("comment"),
        COMMENT_LOCAL("comment_local"),
        CREATE_CHILD("create_child"),
        EDIT("edit"),
        EDIT_LOCAL("edit_local"),
        MANAGE("manage"),
        MANAGE_LOCAL("manage_local"),
        VIEW("view"),
        VIEW_LOCAL("view_local");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Folder() {}
}
