package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Canonical relation and permission names for <b>group</b>.
 * Generated by AuthxCodegen at 2026-04-11T08:58:02.605669Z — do not edit.
 */
public final class Group {

    /** Relations — used with TypedHandle.grant / revoke. */
    public enum Rel implements Relation.Named {
        MEMBER("member");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    private Group() {}
}
