package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Canonical relation and permission names for <b>organization</b>.
 * Generated by AuthxCodegen at 2026-04-11T08:58:02.604162Z — do not edit.
 */
public final class Organization {

    /** Relations — used with TypedHandle.grant / revoke. */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with TypedHandle.check / who / findBy. */
    public enum Perm implements Permission.Named {
        ACCESS("access"),
        MANAGE("manage");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Organization() {}
}
