package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Type-safe enums for the <b>organization</b> definition.
 * Generated by AuthxCodegen at 2026-04-07T06:43:47.531363Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Organization.Rel.EDITOR, "bob");
 * doc.check("doc-1", Organization.Perm.VIEW, "alice");
 * </pre>
 */
public final class Organization {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions (used in check / lookup / who). */
    public enum Perm implements Permission.Named {
        ACCESS("access"),
        MANAGE("manage");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Organization() {}
}
