package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Canonical relation and permission names for <b>space</b>.
 * Generated by AuthxCodegen at 2026-04-11T08:58:02.604944Z — do not edit.
 */
public final class Space {

    /** Relations — used with TypedHandle.grant / revoke. */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member"),
        ORG("org"),
        OWNER("owner"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions — used with TypedHandle.check / who / findBy. */
    public enum Perm implements Permission.Named {
        EDIT("edit"),
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Space() {}
}
