package com.authx.testapp.schema.constants;

import com.authx.sdk.model.Permission;
import com.authx.sdk.model.Relation;

/**
 * Type-safe enums for the <b>space</b> definition.
 * Generated by AuthxCodegen at 2026-04-07T04:26:05.336567Z — do not edit.
 *
 * <pre>
 * // Compile-time safe:
 * doc.grant("doc-1", Space.Rel.EDITOR, "bob");
 * doc.check("doc-1", Space.Perm.VIEW, "alice");
 * </pre>
 */
public final class Space {

    /** Relations (used in grant / revoke). */
    public enum Rel implements Relation.Named {
        ADMIN("admin"),
        MEMBER("member"),
        ORG("org"),
        OWNER("owner"),
        VIEWER("viewer");

        private final String value;
        Rel(String v) { this.value = v; }
        @Override public String relationName() { return value; }
    }

    /** Permissions (used in check / lookup / who). */
    public enum Perm implements Permission.Named {
        EDIT("edit"),
        MANAGE("manage"),
        VIEW("view");

        private final String value;
        Perm(String v) { this.value = v; }
        @Override public String permissionName() { return value; }
    }

    private Space() {}
}
